/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.8.0
 */

/**
 * Advancer/decliner counts within a basket.
 */
export interface AdvanceDeclineSummary {
  /** @minimum 0 */
  advancers: number;
  /** @minimum 0 */
  decliners: number;
  /**
   * @minimum 0
   * @nullable
   */
  unchanged?: number | null;
}
