/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.7.0
 */

export type AlertEventMode = typeof AlertEventMode[keyof typeof AlertEventMode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AlertEventMode = {
  EOD: 'EOD',
  INTRADAY: 'INTRADAY',
} as const;
