/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.8.0
 */

export type AlertEventTriggeredBy = typeof AlertEventTriggeredBy[keyof typeof AlertEventTriggeredBy];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AlertEventTriggeredBy = {
  SCHEDULE: 'SCHEDULE',
  MANUAL: 'MANUAL',
  STARTUP_CATCHUP: 'STARTUP_CATCHUP',
} as const;
