/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.7.0
 */
import type { AlertDeliveryAttemptResponseMeta } from './alertDeliveryAttemptResponseMeta';
import type { AlertDeliveryAttemptStatus } from './alertDeliveryAttemptStatus';

/**
 * Raw delivery attempt recorded for an alert event.
 */
export interface AlertDeliveryAttempt {
  /** @minimum 1 */
  attempt_no?: number;
  /** Channel identifier (e.g., ntfy, email, webhook). */
  channel?: string;
  /** @nullable */
  response_code?: number | null;
  /** @nullable */
  response_meta?: AlertDeliveryAttemptResponseMeta;
  /** @nullable */
  sent_at_utc?: string | null;
  status?: AlertDeliveryAttemptStatus;
}
