/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.7.0
 */

/**
 * Final status for the most recent attempt.
 */
export type AlertChannelStatusStatus = typeof AlertChannelStatusStatus[keyof typeof AlertChannelStatusStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AlertChannelStatusStatus = {
  SENT: 'SENT',
  FAILED: 'FAILED',
  SKIPPED: 'SKIPPED',
} as const;
