/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.7.0
 */
import type { AlertRule } from './alertRule';

export interface AlertState {
  id?: number;
  /** @nullable */
  last_fired_at?: string | null;
  /** @nullable */
  muted_until?: string | null;
  rule?: AlertRule;
}
