/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.8.0
 */
import type { AlertEventChannelsSummaryJson } from './alertEventChannelsSummaryJson';
import type { AlertEventContextJson } from './alertEventContextJson';
import type { AlertDeliveryAttempt } from './alertDeliveryAttempt';
import type { AlertEventDetailsJson } from './alertEventDetailsJson';
import type { AlertEventDigestBucket } from './alertEventDigestBucket';
import type { AlertEventMode } from './alertEventMode';
import type { AlertEventSendType } from './alertEventSendType';
import type { AlertEventSeverity } from './alertEventSeverity';
import type { AlertEventTriggeredBy } from './alertEventTriggeredBy';

export interface AlertEvent {
  body_rendered: string;
  bucket_ord: number;
  /** @nullable */
  channels_summary_json?: AlertEventChannelsSummaryJson;
  /** @nullable */
  config_version?: number | null;
  /** @nullable */
  context_json?: AlertEventContextJson;
  /** @nullable */
  deliveries?: AlertDeliveryAttempt[] | null;
  /** @nullable */
  details_json?: AlertEventDetailsJson;
  digest_bucket: AlertEventDigestBucket;
  /** @nullable */
  digest_id?: string | null;
  fired_at_utc: string;
  id: number;
  /** @nullable */
  intraday_bucket_label?: string | null;
  mode: AlertEventMode;
  /** @nullable */
  next_action_code?: string | null;
  /** @nullable */
  profile?: string | null;
  rule_code: string;
  /** @nullable */
  score_at_fire?: number | null;
  send_type: AlertEventSendType;
  severity: AlertEventSeverity;
  symbol: string;
  title_rendered: string;
  trading_date: string;
  triggered_by?: AlertEventTriggeredBy;
}
