/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.8.0
 */
import type { AlertChannelStatusStatus } from './alertChannelStatusStatus';

/**
 * Aggregated delivery outcome for a single channel.
 */
export interface AlertChannelStatus {
  /**
   * Attempts performed for this channel.
   * @minimum 1
   * @nullable
   */
  attempts?: number | null;
  /**
   * Response/status code returned by channel (if any).
   * @nullable
   */
  code?: number | null;
  /**
   * Reason for skipped/failed delivery (if available).
   * @nullable
   */
  reason?: string | null;
  /** Final status for the most recent attempt. */
  status?: AlertChannelStatusStatus;
}
