/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.8.0
 */

export interface BuyCheck {
  /** Formatted value observed for the gate. */
  actual: string;
  /** Stable identifier for the gate factor. */
  code: string;
  /** Human-readable gate name. */
  label: string;
  /** Indicates whether the gate passed. */
  pass: boolean;
  /** Textual rule applied to the gate. */
  rule: string;
  /**
   * Optional numeric representation of the observed value.
   * @nullable
   */
  value?: number | null;
}
