/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.8.0
 */

export type CandidatePoolEntryStatus = typeof CandidatePoolEntryStatus[keyof typeof CandidatePoolEntryStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CandidatePoolEntryStatus = {
  strong: 'strong',
  weakening: 'weakening',
  exit_soon: 'exit_soon',
  removed: 'removed',
} as const;
