/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.8.0
 */

/**
 * Exit rule identifier.
 */
export type CandidatePoolExitCheckCode = typeof CandidatePoolExitCheckCode[keyof typeof CandidatePoolExitCheckCode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CandidatePoolExitCheckCode = {
  ema20: 'ema20',
  adx14: 'adx14',
  prox52w: 'prox52w',
  age: 'age',
} as const;
