/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.8.0
 */
import type { CandidatePoolExitCheck } from './candidatePoolExitCheck';
import type { CandidatePoolEntryStatus } from './candidatePoolEntryStatus';

export interface CandidatePoolEntry {
  /**
   * EOD as-of label used when the symbol was added.
   * @nullable
   */
  added_as_of?: string | null;
  /** @nullable */
  added_at?: string | null;
  /** Trading date when the symbol first entered the pool. */
  added_on: string;
  /** @nullable */
  added_run_id?: string | null;
  /** @nullable */
  adx14?: number | null;
  /** @nullable */
  atr_pct?: number | null;
  /** @nullable */
  ema20?: number | null;
  exit_checks: CandidatePoolExitCheck[];
  /** True when this is the current BUY_SELECTED candidate (rank */
  is_top_candidate?: boolean;
  /** @nullable */
  last_price?: number | null;
  /** @nullable */
  last_seen_as_of?: string | null;
  /** @nullable */
  last_seen_run_id?: string | null;
  /** @nullable */
  liquidity?: number | null;
  /** @nullable */
  prox_52w_high_pct?: number | null;
  /** @nullable */
  r_multiple?: number | null;
  rank: number;
  /**
   * Weighted score used for ordering the pool (0..1 normalized).
   * @nullable
   */
  rank_score?: number | null;
  reasons?: string[];
  /** @nullable */
  score?: number | null;
  /** True when no fresh snapshot updated this member on the latest run. */
  stale?: boolean;
  status: CandidatePoolEntryStatus;
  symbol: string;
}
