/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.8.0
 */

export interface Counts {
  /** @nullable */
  rows_written?: number | null;
  /** @nullable */
  symbols_processed?: number | null;
}
