/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.8.0
 */
import type { DrawerAlertEventChannelsSummary } from './drawerAlertEventChannelsSummary';

export interface DrawerAlertEvent {
  /**
   * Rendered alert body/summary text.
   * @nullable
   */
  body?: string | null;
  /**
   * Delivery status keyed by channel.
   * @nullable
   */
  channels_summary?: DrawerAlertEventChannelsSummary;
  /** Digest bucket classification. */
  digest_bucket: string;
  /** Timestamp when the alert fired (UTC). */
  fired_at_utc: string;
  id: number;
  /**
   * Snapshot mode when alert fired.
   * @nullable
   */
  mode?: string | null;
  /**
   * Next action code at the time of firing.
   * @nullable
   */
  next_action_code?: string | null;
  /** Rule identifier that triggered the alert. */
  rule_code: string;
  /**
   * Momentum score at the time of firing.
   * @nullable
   */
  score_at_fire?: number | null;
  /** Normalized severity label. */
  severity: string;
  symbol: string;
  /** Rendered alert title. */
  title: string;
  /** Trading date associated with the alert. */
  trading_day: string;
}
