/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.7.0
 */

export type DrawerActionBlockStopMethod = typeof DrawerActionBlockStopMethod[keyof typeof DrawerActionBlockStopMethod];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DrawerActionBlockStopMethod = {
  ATRxK: 'ATRxK',
  EMA_tight: 'EMA_tight',
} as const;
