/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.8.0
 */
import type { DrawerNextActionCode } from './drawerNextActionCode';
import type { DrawerNextActionRefs } from './drawerNextActionRefs';

export interface DrawerNextAction {
  code: DrawerNextActionCode;
  reasons?: string[];
  /** Numeric references used in the text (e.g., S/E/pivot/entry/A/B). */
  refs: DrawerNextActionRefs;
  text: string;
}
