/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.8.0
 */

export interface DrawerDiagnosticsBuyChecklistItem {
  /** Stable identifier for the gate factor. */
  code: string;
  /** Short explanation of what the outcome means. */
  description: string;
  /** Human-readable gate name. */
  factor: string;
  /** True when the gate passed. */
  passed: boolean;
  /**
   * Formatted rule or threshold.
   * @nullable
   */
  rule_display?: string | null;
  /** Formatted observed value. */
  value_display: string;
  /** Combined display of the value against the rule. */
  value_vs_rule: string;
}
