/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.7.0
 */

/**
 * Evaluation mode used for the gate checks.
 */
export type DrawerDiagnosticsBuyChecklistMode = typeof DrawerDiagnosticsBuyChecklistMode[keyof typeof DrawerDiagnosticsBuyChecklistMode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DrawerDiagnosticsBuyChecklistMode = {
  EOD: 'EOD',
  INTRADAY: 'INTRADAY',
} as const;
