/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.8.0
 */
import type { DrawerActionBlockBreakevenState } from './drawerActionBlockBreakevenState';
import type { DrawerActionBlockEuphoriaState } from './drawerActionBlockEuphoriaState';
import type { DrawerActionBlockStopMethod } from './drawerActionBlockStopMethod';

export interface DrawerActionBlock {
  breakeven_state: DrawerActionBlockBreakevenState;
  euphoria_state: DrawerActionBlockEuphoriaState;
  /** @nullable */
  exit_close_threshold?: number | null;
  /** @nullable */
  stop_method?: DrawerActionBlockStopMethod;
  /** @nullable */
  stop_now?: number | null;
}
