/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.7.0
 */
import type { AlertTemplate } from './alertTemplate';
import type { Badge } from './badge';
import type { Channels } from './channels';
import type { Indicators } from './indicators';
import type { DrawerDetailMeters } from './drawerDetailMeters';
import type { NextAction } from './nextAction';
import type { Position } from './position';

export interface DrawerDetail {
  alert_templates?: AlertTemplate[];
  as_of?: string;
  badges?: Badge[];
  channels?: Channels;
  indicators?: Indicators;
  meters?: DrawerDetailMeters;
  method_pill?: string;
  name?: string;
  next_action?: NextAction;
  pct_today?: number;
  position?: Position;
  price?: number;
  run_id?: string;
  score?: number;
  sector?: string;
  symbol?: string;
  symbol_canon?: string;
}
