/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.7.0
 */
import type { DrawerDiagnosticsBuyChecklistItem } from './drawerDiagnosticsBuyChecklistItem';
import type { DrawerDiagnosticsBuyChecklistMode } from './drawerDiagnosticsBuyChecklistMode';

export interface DrawerDiagnosticsBuyChecklist {
  /**
   * Short summary of failing gates when the checklist fails.
   * @nullable
   */
  fail_summary?: string | null;
  items: DrawerDiagnosticsBuyChecklistItem[];
  /** Display label for this checklist section. */
  label: string;
  /** Evaluation mode used for the gate checks. */
  mode: DrawerDiagnosticsBuyChecklistMode;
  /** True when the enforced gates passed. */
  passed: boolean;
  /** Count of gates that passed. */
  passed_items: number;
  /** Human-readable verdict aligned with the buy flag. */
  summary: string;
  /** Total gates evaluated. */
  total_items: number;
}
