/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.7.0
 */

export interface DrawerSelection {
  /** @nullable */
  r_multiple?: number | null;
  /** @nullable */
  reason?: string | null;
  /** @nullable */
  run_id?: string | null;
  selected?: boolean;
  /** @nullable */
  stop_price?: number | null;
  /** @nullable */
  target_price?: number | null;
  /** @nullable */
  trading_day?: string | null;
}
