/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.7.0
 */
import type { DrawerDiagnosticsBuyChecklist } from './drawerDiagnosticsBuyChecklist';
import type { BuyEvaluation } from './buyEvaluation';

export interface DrawerDiagnostics {
  /** @nullable */
  blocked_reason?: string | null;
  buy_checklist?: DrawerDiagnosticsBuyChecklist;
  buy_evaluation?: BuyEvaluation;
  /** @nullable */
  buy_failed_codes?: string[] | null;
  /** @nullable */
  buy_reasons_inline?: string | null;
  reason: string;
  /**
   * Optional natural-language explanation; may be same as reason.
   * @nullable
   */
  reason_text?: string | null;
  rules_version: string;
}
