/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.7.0
 */
import type { GetApiV1ScreenerSortBy } from './getApiV1ScreenerSortBy';
import type { GetApiV1ScreenerSortDir } from './getApiV1ScreenerSortDir';
import type { GetApiV1ScreenerUniverse } from './getApiV1ScreenerUniverse';

export type GetApiV1ScreenerParams = {
page?: number;
per_page?: number;
sort_by?: GetApiV1ScreenerSortBy;
sort_dir?: GetApiV1ScreenerSortDir;
universe?: GetApiV1ScreenerUniverse;
/**
 * Exact ticker symbol (case-insensitive)
 */
symbol?: string;
sector_in?: string[];
score_min?: number;
rsi_min?: number;
rsi_max?: number;
adx_min?: number;
price_min?: number;
price_max?: number;
pct_today_min?: number;
proximity_52w_high_max?: number;
watchlist_only?: boolean;
stale_exclude?: boolean;
run_id?: string;
};
