/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.7.0
 */

export type GetApiV1ScreenerSortDir = typeof GetApiV1ScreenerSortDir[keyof typeof GetApiV1ScreenerSortDir];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiV1ScreenerSortDir = {
  asc: 'asc',
  desc: 'desc',
} as const;
