/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.8.0
 */

export type GetApiV1ScreenerSortBy = typeof GetApiV1ScreenerSortBy[keyof typeof GetApiV1ScreenerSortBy];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiV1ScreenerSortBy = {
  score: 'score',
  pct_today: 'pct_today',
  rsi: 'rsi',
  adx: 'adx',
  proximity_52w_high: 'proximity_52w_high',
  relvol20: 'relvol20',
  price: 'price',
  name: 'name',
  sector: 'sector',
  wk_change: 'wk_change',
  wk_change_pct: 'wk_change_pct',
} as const;
