/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.8.0
 */

export type GetMomentumHeatmapParams = {
/**
 * Optional trading date (YYYY-MM-DD, IST) to retrieve a historical snapshot; defaults to the latest available run.

 */
as_of?: string;
/**
 * Include industry-level breakdown nested within each sector.
 */
include_industries?: boolean;
/**
 * Include top/bottom constituent momentum summaries for each node.
 */
include_constituents?: boolean;
};
