/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.7.0
 */
import type { GetNewsListSort } from './getNewsListSort';

export type GetNewsListParams = {
symbol: string;
from: string;
to: string;
page?: number;
per_page?: number;
min_confidence?: number;
/**
 * CSV of event types
 */
event?: string;
sort?: GetNewsListSort;
};
