/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.7.0
 */
import type { ScreenerRunMode } from './screenerRunMode';

export type GetScreenerRunsParams = {
/**
 * Snapshot category to inspect.
 */
mode?: ScreenerRunMode;
/**
 * Trading date (YYYY-MM-DD). Required when `mode=intraday`.
 */
trade_date?: string;
/**
 * End-of-day snapshot date (YYYY-MM-DD). Required when `mode=eod`.
 */
as_of?: string;
/**
 * Maximum number of runs to return (intraday only).
 */
limit?: number;
};
