/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.7.0
 */
import type { ScreenerRunMode } from './screenerRunMode';

export type GetScreenerRunDatesParams = {
/**
 * Snapshot category to inspect. Defaults to `intraday`.
 */
mode?: ScreenerRunMode;
/**
 * Maximum number of dates to return (most recent first).
 */
limit?: number;
};
