/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.7.0
 */

export type GetScreenerUniverse = typeof GetScreenerUniverse[keyof typeof GetScreenerUniverse];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetScreenerUniverse = {
  NIFTY50: 'NIFTY50',
  NIFTY100: 'NIFTY100',
  NIFTY500: 'NIFTY500',
  MIDCAP: 'MIDCAP',
  SMALLCAP: 'SMALLCAP',
  ALL: 'ALL',
} as const;
