/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.8.0
 */

export type GetTopMoversPeriod = typeof GetTopMoversPeriod[keyof typeof GetTopMoversPeriod];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetTopMoversPeriod = {
  '1d': '1d',
  '1w': '1w',
  '1m': '1m',
  '3m': '3m',
  '6m': '6m',
  '1y': '1y',
  '5y': '5y',
  custom: 'custom',
} as const;
