/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.8.0
 */
import type { GetTopMoversPeriod } from './getTopMoversPeriod';

export type GetTopMoversParams = {
/**
 * Period over which to compute percentage change
 */
period?: GetTopMoversPeriod;
/**
 * Custom period start date; only valid when period is custom
 */
start_date?: string | null;
/**
 * Custom period end date; only valid when period is custom
 */
end_date?: string | null;
};
