/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.7.0
 */

export type IndicatorPointKey = typeof IndicatorPointKey[keyof typeof IndicatorPointKey];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IndicatorPointKey = {
  rsi: 'rsi',
  adx: 'adx',
  ema12: 'ema12',
  ema26: 'ema26',
  ema50: 'ema50',
  ema200: 'ema200',
  obv: 'obv',
  relvol: 'relvol',
} as const;
