/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.7.0
 */

export interface Indicators {
  adx_slope?: number;
  adx14?: number;
  ema_fast?: number;
  ema_fast_value?: number;
  ema_slow?: number;
  ema_slow_value?: number;
  proximity_52w_high_pct?: number;
  relvol20?: number;
  rsi14?: number;
}
