/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.8.0
 */
import type { UniverseInstrument } from './universeInstrument';
import type { Pagination } from './pagination';

export type ListUniverse200 = {
  items?: UniverseInstrument[];
  pagination?: Pagination;
};
