/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.7.0
 */

export type ListAllNewsAlign = typeof ListAllNewsAlign[keyof typeof ListAllNewsAlign];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListAllNewsAlign = {
  trading_day: 'trading_day',
  calendar_day: 'calendar_day',
} as const;
