/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.7.0
 */
import type { ListAllNewsAlign } from './listAllNewsAlign';
import type { ListAllNewsSort } from './listAllNewsSort';

export type ListAllNewsParams = {
/**
 * Optional symbol filter (e.g., RELIANCE.NS)
 */
symbol?: string;
/**
 * Trading date (YYYY-MM-DD) in IST; ignored if explicit from/to provided
 */
on?: string;
align?: ListAllNewsAlign;
from?: string;
to?: string;
page?: number;
per_page?: number;
min_confidence?: number;
/**
 * CSV of event types
 */
event?: string;
sort?: ListAllNewsSort;
};
