/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.7.0
 */
import type { ListNewsBySymbolAlign } from './listNewsBySymbolAlign';
import type { ListNewsBySymbolSort } from './listNewsBySymbolSort';

export type ListNewsBySymbolParams = {
symbol: string;
/**
 * Trading date (YYYY-MM-DD) in IST; ignored if from/to present
 */
on?: string;
align?: ListNewsBySymbolAlign;
from?: string;
to?: string;
page?: number;
per_page?: number;
min_confidence?: number;
/**
 * Comma-separated event types (e.g., results,pledge,order_win)
 */
event?: string;
sort?: ListNewsBySymbolSort;
};
