/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.8.0
 */
import type { MeterBasis } from './meterBasis';
import type { MeterLevel } from './meterLevel';
import type { MeterThresholds } from './meterThresholds';

export interface Meter {
  /** Raw inputs used to compute the meter (e.g., atr14_pct, rsi14, adx14). */
  basis: MeterBasis;
  level: MeterLevel;
  /**
   * Quantitative calibration for the meter; null if not computable.
   * @minimum 0
   * @maximum 100
   * @nullable
   */
  score_0_100: number | null;
  thresholds: MeterThresholds;
}
