/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.8.0
 */

/**
 * Raw inputs used to compute the meter (e.g., atr14_pct, rsi14, adx14).
 */
export type MeterBasis = { [key: string]: unknown };
