/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.7.0
 */
import type { AdvanceDeclineSummary } from './advanceDeclineSummary';
import type { MomentumHeatmapIndustry } from './momentumHeatmapIndustry';
import type { MomentumHeatmapConstituent } from './momentumHeatmapConstituent';
import type { MomentumHeatmapSectorAllOfLevel } from './momentumHeatmapSectorAllOfLevel';

export type MomentumHeatmapSectorAllOf = {
  advance_decline?: AdvanceDeclineSummary;
  industries?: MomentumHeatmapIndustry[];
  laggards?: MomentumHeatmapConstituent[];
  leaders?: MomentumHeatmapConstituent[];
  level?: MomentumHeatmapSectorAllOfLevel;
  /**
   * NSE traded value for the index (INR crore).
   * @nullable
   */
  total_turnover_cr?: number | null;
};
