/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.8.0
 */
import type { MomentumHeatmapNodeBase } from './momentumHeatmapNodeBase';
import type { MomentumHeatmapSectorAllOf } from './momentumHeatmapSectorAllOf';

export type MomentumHeatmapSector = MomentumHeatmapNodeBase & MomentumHeatmapSectorAllOf;
