/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.7.0
 */
import type { MomentumHeatmapConstituent } from './momentumHeatmapConstituent';
import type { MomentumHeatmapIndustryAllOfLevel } from './momentumHeatmapIndustryAllOfLevel';

export type MomentumHeatmapIndustryAllOf = {
  laggards?: MomentumHeatmapConstituent[];
  leaders?: MomentumHeatmapConstituent[];
  level?: MomentumHeatmapIndustryAllOfLevel;
  /** NSE sector symbol this industry rolls into. */
  parent_symbol?: string;
  /** @nullable */
  total_turnover_cr?: number | null;
};
