/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.7.0
 */
import type { MomentumHeatmapResponseMetadata } from './momentumHeatmapResponseMetadata';
import type { RunId } from './runId';
import type { MomentumHeatmapSector } from './momentumHeatmapSector';
import type { MomentumHeatmapResponseSession } from './momentumHeatmapResponseSession';

export interface MomentumHeatmapResponse {
  /** IST timestamp when this snapshot was computed. */
  as_of: string;
  /**
   * Age in seconds of the newest upstream datapoint.
   * @minimum 0
   */
  latency_sec?: number;
  /** @nullable */
  metadata?: MomentumHeatmapResponseMetadata;
  /** @nullable */
  notes?: string[] | null;
  run_id?: RunId;
  /** @minItems 1 */
  sectors: MomentumHeatmapSector[];
  /** NSE market session corresponding to the data. */
  session: MomentumHeatmapResponseSession;
  source?: string;
  /** Trading date aligned to NSE calendar. */
  trade_date: string;
}
