/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.7.0
 */

/**
 * Normalized catalyst/event category for a news item
 */
export type NewsEventType = typeof NewsEventType[keyof typeof NewsEventType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NewsEventType = {
  results: 'results',
  order_win: 'order_win',
  pledge: 'pledge',
  rating_change: 'rating_change',
  regulatory: 'regulatory',
  court: 'court',
  mna: 'mna',
  guidance: 'guidance',
  mgmt_change: 'mgmt_change',
  macro: 'macro',
  other: 'other',
} as const;
