/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.8.0
 */
import type { NewsCard } from './newsCard';
import type { NewsWindowListResponseWindow } from './newsWindowListResponseWindow';

export interface NewsWindowListResponse {
  items: NewsCard[];
  /** @nullable */
  next_page?: number | null;
  /** @nullable */
  note?: string | null;
  page: number;
  per_page: number;
  window: NewsWindowListResponseWindow;
}
