/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.8.0
 */
import type { NewsEventType } from './newsEventType';
import type { NewsSentiment } from './newsSentiment';
import type { NewsSourceRef } from './newsSourceRef';

export interface NewsIngestItem {
  /** @minItems 1 */
  bullets: string[];
  cluster_id: string;
  /**
   * @minimum 1
   * @maximum 3
   */
  confidence_stars: number;
  /**
   * @minimum 0
   * @maximum 1
   */
  consensus_score: number;
  event_type: NewsEventType;
  published: string;
  sentiment: NewsSentiment;
  /** @minimum 1 */
  source_count: number;
  sources: NewsSourceRef[];
  symbol: string;
  title: string;
  why: string;
}
