/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.7.0
 */
import type { NewsEventType } from './newsEventType';
import type { NewsSentiment } from './newsSentiment';
import type { NewsSourceRef } from './newsSourceRef';

export interface NewsCard {
  /**
   * 2–5 factual points; engine decides length
   * @minItems 1
   */
  bullets: string[];
  cluster_id: string;
  /**
   * @minimum 1
   * @maximum 3
   */
  confidence_stars: number;
  /**
   * @minimum 0
   * @maximum 1
   */
  consensus_score?: number;
  /**
   * e.g., "Appeared 12m before price spike"
   * @nullable
   */
  correlation_note?: string | null;
  event_type: NewsEventType;
  /**
   * Ranking score used when explaining a move
   * @minimum 0
   * @maximum 1
   * @nullable
   */
  impact_score?: number | null;
  /** Earliest seen publish time (IST) */
  published: string;
  sentiment?: NewsSentiment;
  /** @minimum 1 */
  source_count: number;
  /**
   * Primary publisher for display (first source)
   * @nullable
   */
  source_primary?: string | null;
  /**
   * Primary URL for display (first source)
   * @nullable
   */
  source_url?: string | null;
  sources: NewsSourceRef[];
  /** Canonical symbol tagged to this news cluster */
  symbol: string;
  title: string;
  /** One-line reason why this matters for price/momentum */
  why: string;
}
