/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.8.0
 */

/**
 * High-level recommendation verb
 */
export type NextActionAction = typeof NextActionAction[keyof typeof NextActionAction];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NextActionAction = {
  BUY: 'BUY',
  HOLD: 'HOLD',
  SELL: 'SELL',
  WATCH: 'WATCH',
  ADD: 'ADD',
  TRIM: 'TRIM',
  REDUCE: 'REDUCE',
} as const;
