/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.7.0
 */
import type { NextActionAction } from './nextActionAction';
import type { NextActionRefs } from './nextActionRefs';

export interface NextAction {
  /** High-level recommendation verb */
  action?: NextActionAction;
  code?: string;
  reasons?: string[];
  refs?: NextActionRefs;
  text?: string;
}
