/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.7.0
 */

export interface PositionOut {
  breakeven_active?: boolean;
  created_at: string;
  /** @nullable */
  entry_price_locked?: number | null;
  euphoria_on?: boolean;
  /** @nullable */
  exit_close_threshold?: number | null;
  id: number;
  /** @nullable */
  note?: string | null;
  /** @nullable */
  qty?: number | null;
  /**
   * Realized profit/loss (INR) when trade is closed.
   * @nullable
   */
  realized_pl?: number | null;
  /**
   * Realized profit/loss percentage relative to entry.
   * @nullable
   */
  realized_pl_pct?: number | null;
  /** @nullable */
  sell_price?: number | null;
  /** @nullable */
  sold_at?: string | null;
  /** @nullable */
  stop_now?: number | null;
  symbol: string;
  trade_on: boolean;
  updated_at: string;
}
