/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.7.0
 */

/**
 * Partial update used by PUT /api/v1/positions/{symbol}. All fields are optional; only send the fields you want to set/update. Server canonicalizes the symbol from the path and returns a PositionOut.

 */
export interface PositionUpsert {
  /** Whether breakeven rule is active. */
  breakeven_active?: boolean;
  /**
   * Locked entry chosen by user (₹).
   * @minimum 0
   */
  entry_price_locked?: number;
  /** Whether “euphoria” guardrail is active. */
  euphoria_on?: boolean;
  /**
   * Close-below threshold to trigger exit (₹).
   * @minimum 0
   */
  exit_close_threshold?: number;
  /**
   * Free-form note saved with the position.
   * @maxLength 2000
   */
  note?: string;
  /**
   * Position size (shares/units).
   * @minimum 0
   */
  qty?: number;
  /**
   * Optional exit price when closing (INR).
   * @minimum 0
   */
  sell_price?: number;
  /** Timestamp trade was closed (UTC). */
  sold_at?: string;
  /**
   * Current trailing/soft stop level (₹).
   * @minimum 0
   */
  stop_now?: number;
  /** Whether trade/position is active for this symbol. */
  trade_on?: boolean;
}
