/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.7.0
 */
import type { ProblemCode } from './problemCode';
import type { ProblemErrorsItem } from './problemErrorsItem';

export interface Problem {
  /** App-specific error code */
  code?: ProblemCode;
  detail?: string;
  errors?: ProblemErrorsItem[];
  instance?: string;
  status: number;
  title: string;
  type: string;
}
