/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.7.0
 */

/**
 * App-specific error code
 */
export type ProblemCode = typeof ProblemCode[keyof typeof ProblemCode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProblemCode = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  RATE_LIMITED: 'RATE_LIMITED',
  SNAPSHOT_CONFLICT: 'SNAPSHOT_CONFLICT',
  NOT_FOUND: 'NOT_FOUND',
} as const;
