/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.7.0
 */
import type { RunSummaryBaseStatus } from './runSummaryBaseStatus';

export interface RunSummaryBase {
  /** @nullable */
  ended_at?: string | null;
  job_name?: string;
  /**
   * UTC timestamp yyyymmddHHMMss
   * @pattern ^[0-9]{14}$
   */
  run_id?: string;
  started_at?: string;
  status?: RunSummaryBaseStatus;
}
