/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.7.0
 */

export interface Score {
  adx_component?: number;
  momentum_12_1m?: number;
  momentum_1m?: number;
  momentum_3m?: number;
  momentum_6m?: number;
  rsi_component?: number;
  total?: number;
  volatility_penalty?: number;
}
