/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.7.0
 */
import type { Badge } from './badge';
import type { BuyCheck } from './buyCheck';

export interface ScreenerRow {
  adx?: number;
  as_of?: string;
  atr_pct?: number;
  badges?: Badge[];
  buy?: boolean;
  buy_flag?: boolean;
  buy_profile?: string;
  buy_mode?: 'EOD' | 'INTRADAY';
  buy_pass_count?: number;
  buy_total_count?: number;
  buy_checks?: BuyCheck[];
  buy_failed_codes?: string[];
  buy_reasons_inline?: string;
  buy_eval_ts?: string;
  /** @nullable */
  buy_enforced_checks?: string[] | null;
  /** @nullable */
  buy_reason_parts?: string[] | null;
  /** @nullable */
  buy_selected?: boolean | null;
  /** @nullable */
  buy_selection_reason?: string | null;
  /** @nullable */
  buy_stop_price?: number | null;
  /** @nullable */
  buy_target_price?: number | null;
  /** @nullable */
  buy_r_multiple?: number | null;
  /** @nullable */
  buy_selection_run_id?: string | null;
  /** @nullable */
  buy_selection_trading_day?: string | null;
  change_pct: number;
  last: number;
  last_index?: string;
  liquidity?: number;
  name?: string;
  pct_from_52w_high?: number;
  pct_today?: number;
  reason?: string;
  ret_12_1m?: number;
  ret_1m?: number;
  ret_3m?: number;
  ret_6m?: number;
  rsi?: number;
  run_id?: string;
  score: number;
  sector?: string;
  source?: string;
  stale?: boolean;
  strength?: string;
  symbol: string;
  vol_spike?: number;
  /** @nullable */
  wk_change?: number | null;
  /** @nullable */
  wk_change_pct?: number | null;
}
