/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.7.0
 */
import type { Badge } from './badge';

export interface ScreenerRow {
  adx?: number;
  as_of?: string;
  atr_pct?: number;
  badges?: Badge[];
  buy?: boolean;
  change_pct: number;
  last: number;
  last_index?: string;
  liquidity?: number;
  name?: string;
  pct_from_52w_high?: number;
  pct_today?: number;
  reason?: string;
  ret_12_1m?: number;
  ret_1m?: number;
  ret_3m?: number;
  ret_6m?: number;
  rsi?: number;
  run_id?: string;
  score: number;
  sector?: string;
  source?: string;
  stale?: boolean;
  strength?: string;
  symbol: string;
  vol_spike?: number;
  /** @nullable */
  wk_change?: number | null;
  /** @nullable */
  wk_change_pct?: number | null;
}
