/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.8.0
 */
import type { ScreenerRunMode } from './screenerRunMode';

export interface ScreenerRunDate {
  /**
   * End-of-day snapshot date (YYYY-MM-DD).
   * @nullable
   */
  as_of?: string | null;
  /**
   * Short label suitable for dropdowns/calendars.
   * @nullable
   */
  label?: string | null;
  mode: ScreenerRunMode;
  /**
   * Number of runs committed for this date.
   * @minimum 0
   */
  run_count: number;
  /**
   * Trading date (YYYY-MM-DD) for intraday snapshots.
   * @nullable
   */
  trade_date?: string | null;
}
