/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.8.0
 */
import type { ScreenerRow } from './screenerRow';
import type { Pagination } from './pagination';

export interface ScreenerList {
  /**
   * Snapshot timestamp (UTC)
   * @nullable
   */
  as_of?: string | null;
  items?: ScreenerRow[];
  pagination?: Pagination;
  /**
   * Run identifier used for this list
   * @nullable
   */
  run_id?: string | null;
}
