/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.8.0
 */

/**
 * Evaluation mode used for the buy gates.
 * @nullable
 */
export type ScreenerRowBuyMode = typeof ScreenerRowBuyMode[keyof typeof ScreenerRowBuyMode] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ScreenerRowBuyMode = {
  EOD: 'EOD',
  INTRADAY: 'INTRADAY',
} as const;
