/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.7.0
 */
import type { ScreenerRunMode } from './screenerRunMode';
import type { RunId } from './runId';

export interface ScreenerRunSummary {
  /**
   * End-of-day snapshot date.
   * @nullable
   */
  as_of?: string | null;
  /**
   * UTC timestamp when the run finished writing the snapshot.
   * @nullable
   */
  completed_at?: string | null;
  /**
   * Human-friendly label (e.g., "12:15 PM IST" or "Fri 24 Oct EOD").
   * @nullable
   */
  label?: string | null;
  mode: ScreenerRunMode;
  /**
   * Snapshot run identifier (intraday or EOD where available).
   * @nullable
   */
  run_id?: RunId;
  /**
   * UTC timestamp when the run started (if tracked).
   * @nullable
   */
  started_at?: string | null;
  /**
   * Trading date (intraday).
   * @nullable
   */
  trade_date?: string | null;
}
