/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.7.0
 */
import type { TopMoverEntry } from './topMoverEntry';
import type { TopMoversPeriod } from './topMoversPeriod';

export interface TopMovers {
  /** @nullable */
  as_of?: string | null;
  gainers: TopMoverEntry[];
  generated_at: string;
  losers: TopMoverEntry[];
  period: TopMoversPeriod;
  /** @nullable */
  run_id?: string | null;
}
