/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.7.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  AddToWatchlistBody,
  AlertRule,
  AlertState,
  DrawerDetail,
  GetInstrumentIndicatorsParams,
  GetInstrumentPricesParams,
  GetInstrumentsSymbolDetailParams,
  GetLearning200,
  GetScreenerParams,
  GetWatchlist200,
  HealthState,
  HistoryRow,
  IndicatorPoint,
  ListHistoryParams,
  ListInstruments200,
  ListInstrumentsParams,
  ListPositionsParams,
  ListRuns200,
  ListRunsParams,
  ListSnapshotPinsParams,
  ListUniverse200,
  ListUniverseParams,
  PositionIn,
  PositionOut,
  PositionUpsert,
  PreviewAlertDigest200,
  PriceCandle,
  Problem,
  RemoveFromWatchlistParams,
  RunDetail,
  RunId,
  ScanRequest,
  ScreenerList,
  SectorFacet,
  Settings,
  SnapshotPinIn,
  SnapshotPinOut
} from './types'




/**
 * @summary Quick health (combined)
 */
export const health = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<HealthState>> => {
    
    return axios.default.get(
      `/health`,options
    );
  }


export const getHealthQueryKey = () => {
    return [`/health`] as const;
    }

    
export const getHealthQueryOptions = <TData = Awaited<ReturnType<typeof health>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof health>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof health>>> = ({ signal }) => health({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof health>>, TError, TData> & { queryKey: QueryKey }
}

export type HealthQueryResult = NonNullable<Awaited<ReturnType<typeof health>>>
export type HealthQueryError = AxiosError<unknown>

/**
 * @summary Quick health (combined)
 */
export const useHealth = <TData = Awaited<ReturnType<typeof health>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof health>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getHealthQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Liveness probe
 */
export const healthLive = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    return axios.default.get(
      `/health/live`,options
    );
  }


export const getHealthLiveQueryKey = () => {
    return [`/health/live`] as const;
    }

    
export const getHealthLiveQueryOptions = <TData = Awaited<ReturnType<typeof healthLive>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthLive>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthLiveQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthLive>>> = ({ signal }) => healthLive({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthLive>>, TError, TData> & { queryKey: QueryKey }
}

export type HealthLiveQueryResult = NonNullable<Awaited<ReturnType<typeof healthLive>>>
export type HealthLiveQueryError = AxiosError<unknown>

/**
 * @summary Liveness probe
 */
export const useHealthLive = <TData = Awaited<ReturnType<typeof healthLive>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthLive>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getHealthLiveQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Readiness probe (SQLite + Parquet availability)
 */
export const healthReady = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    return axios.default.get(
      `/health/ready`,options
    );
  }


export const getHealthReadyQueryKey = () => {
    return [`/health/ready`] as const;
    }

    
export const getHealthReadyQueryOptions = <TData = Awaited<ReturnType<typeof healthReady>>, TError = AxiosError<Problem>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthReady>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthReadyQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthReady>>> = ({ signal }) => healthReady({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthReady>>, TError, TData> & { queryKey: QueryKey }
}

export type HealthReadyQueryResult = NonNullable<Awaited<ReturnType<typeof healthReady>>>
export type HealthReadyQueryError = AxiosError<Problem>

/**
 * @summary Readiness probe (SQLite + Parquet availability)
 */
export const useHealthReady = <TData = Awaited<ReturnType<typeof healthReady>>, TError = AxiosError<Problem>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthReady>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getHealthReadyQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Prometheus metrics (optional)
 */
export const metrics = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<string>> => {
    
    return axios.default.get(
      `/health/metrics`,options
    );
  }


export const getMetricsQueryKey = () => {
    return [`/health/metrics`] as const;
    }

    
export const getMetricsQueryOptions = <TData = Awaited<ReturnType<typeof metrics>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof metrics>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getMetricsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof metrics>>> = ({ signal }) => metrics({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof metrics>>, TError, TData> & { queryKey: QueryKey }
}

export type MetricsQueryResult = NonNullable<Awaited<ReturnType<typeof metrics>>>
export type MetricsQueryError = AxiosError<unknown>

/**
 * @summary Prometheus metrics (optional)
 */
export const useMetrics = <TData = Awaited<ReturnType<typeof metrics>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof metrics>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getMetricsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary List screener rows (filtered, sorted, paginated)
 */
export const getScreener = (
    params?: GetScreenerParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ScreenerList>> => {
    
    return axios.default.get(
      `/screener`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getGetScreenerQueryKey = (params?: GetScreenerParams,) => {
    return [`/screener`, ...(params ? [params]: [])] as const;
    }

    
export const getGetScreenerQueryOptions = <TData = Awaited<ReturnType<typeof getScreener>>, TError = AxiosError<unknown>>(params?: GetScreenerParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getScreener>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetScreenerQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getScreener>>> = ({ signal }) => getScreener(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getScreener>>, TError, TData> & { queryKey: QueryKey }
}

export type GetScreenerQueryResult = NonNullable<Awaited<ReturnType<typeof getScreener>>>
export type GetScreenerQueryError = AxiosError<unknown>

/**
 * @summary List screener rows (filtered, sorted, paginated)
 */
export const useGetScreener = <TData = Awaited<ReturnType<typeof getScreener>>, TError = AxiosError<unknown>>(
 params?: GetScreenerParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getScreener>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetScreenerQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Triggers a new scores snapshot with a fresh run_id. If the same
Idempotency-Key (or ScanRequest.key) is reused, returns the existing run.
On first creation: 201 Created. On idempotent replay: 200 OK.

 * @summary Start a manual screening run (idempotent)
 */
export const postScan = (
    scanRequest?: ScanRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<RunDetail>> => {
    
    return axios.default.post(
      `/scan`,
      scanRequest,options
    );
  }



export const getPostScanMutationOptions = <TError = AxiosError<Problem | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postScan>>, TError,{data: ScanRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postScan>>, TError,{data: ScanRequest}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postScan>>, {data: ScanRequest}> = (props) => {
          const {data} = props ?? {};

          return  postScan(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostScanMutationResult = NonNullable<Awaited<ReturnType<typeof postScan>>>
    export type PostScanMutationBody = ScanRequest
    export type PostScanMutationError = AxiosError<Problem | void>

    /**
 * @summary Start a manual screening run (idempotent)
 */
export const usePostScan = <TError = AxiosError<Problem | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postScan>>, TError,{data: ScanRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof postScan>>,
        TError,
        {data: ScanRequest},
        TContext
      > => {

      const mutationOptions = getPostScanMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary List recent scan runs
 */
export const listRuns = (
    params?: ListRunsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ListRuns200>> => {
    
    return axios.default.get(
      `/runs`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getListRunsQueryKey = (params?: ListRunsParams,) => {
    return [`/runs`, ...(params ? [params]: [])] as const;
    }

    
export const getListRunsQueryOptions = <TData = Awaited<ReturnType<typeof listRuns>>, TError = AxiosError<unknown>>(params?: ListRunsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRuns>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListRunsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listRuns>>> = ({ signal }) => listRuns(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listRuns>>, TError, TData> & { queryKey: QueryKey }
}

export type ListRunsQueryResult = NonNullable<Awaited<ReturnType<typeof listRuns>>>
export type ListRunsQueryError = AxiosError<unknown>

/**
 * @summary List recent scan runs
 */
export const useListRuns = <TData = Awaited<ReturnType<typeof listRuns>>, TError = AxiosError<unknown>>(
 params?: ListRunsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRuns>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getListRunsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Run details
 */
export const getRun = (
    runId: RunId, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<RunDetail>> => {
    
    return axios.default.get(
      `/runs/${runId}`,options
    );
  }


export const getGetRunQueryKey = (runId: RunId,) => {
    return [`/runs/${runId}`] as const;
    }

    
export const getGetRunQueryOptions = <TData = Awaited<ReturnType<typeof getRun>>, TError = AxiosError<Problem>>(runId: RunId, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRun>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRunQueryKey(runId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRun>>> = ({ signal }) => getRun(runId, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(runId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRun>>, TError, TData> & { queryKey: QueryKey }
}

export type GetRunQueryResult = NonNullable<Awaited<ReturnType<typeof getRun>>>
export type GetRunQueryError = AxiosError<Problem>

/**
 * @summary Run details
 */
export const useGetRun = <TData = Awaited<ReturnType<typeof getRun>>, TError = AxiosError<Problem>>(
 runId: RunId, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRun>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetRunQueryOptions(runId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary List/search universe (symbols)
 */
export const listUniverse = (
    params?: ListUniverseParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ListUniverse200>> => {
    
    return axios.default.get(
      `/universe`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getListUniverseQueryKey = (params?: ListUniverseParams,) => {
    return [`/universe`, ...(params ? [params]: [])] as const;
    }

    
export const getListUniverseQueryOptions = <TData = Awaited<ReturnType<typeof listUniverse>>, TError = AxiosError<void>>(params?: ListUniverseParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUniverse>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListUniverseQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listUniverse>>> = ({ signal }) => listUniverse(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listUniverse>>, TError, TData> & { queryKey: QueryKey }
}

export type ListUniverseQueryResult = NonNullable<Awaited<ReturnType<typeof listUniverse>>>
export type ListUniverseQueryError = AxiosError<void>

/**
 * @summary List/search universe (symbols)
 */
export const useListUniverse = <TData = Awaited<ReturnType<typeof listUniverse>>, TError = AxiosError<void>>(
 params?: ListUniverseParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUniverse>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getListUniverseQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Sector facets with counts
 */
export const listSectors = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SectorFacet[]>> => {
    
    return axios.default.get(
      `/universe/sectors`,options
    );
  }


export const getListSectorsQueryKey = () => {
    return [`/universe/sectors`] as const;
    }

    
export const getListSectorsQueryOptions = <TData = Awaited<ReturnType<typeof listSectors>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSectors>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListSectorsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listSectors>>> = ({ signal }) => listSectors({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listSectors>>, TError, TData> & { queryKey: QueryKey }
}

export type ListSectorsQueryResult = NonNullable<Awaited<ReturnType<typeof listSectors>>>
export type ListSectorsQueryError = AxiosError<unknown>

/**
 * @summary Sector facets with counts
 */
export const useListSectors = <TData = Awaited<ReturnType<typeof listSectors>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSectors>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getListSectorsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Search/autocomplete instruments
 */
export const listInstruments = (
    params?: ListInstrumentsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ListInstruments200>> => {
    
    return axios.default.get(
      `/instruments`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getListInstrumentsQueryKey = (params?: ListInstrumentsParams,) => {
    return [`/instruments`, ...(params ? [params]: [])] as const;
    }

    
export const getListInstrumentsQueryOptions = <TData = Awaited<ReturnType<typeof listInstruments>>, TError = AxiosError<unknown>>(params?: ListInstrumentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listInstruments>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListInstrumentsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listInstruments>>> = ({ signal }) => listInstruments(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listInstruments>>, TError, TData> & { queryKey: QueryKey }
}

export type ListInstrumentsQueryResult = NonNullable<Awaited<ReturnType<typeof listInstruments>>>
export type ListInstrumentsQueryError = AxiosError<unknown>

/**
 * @summary Search/autocomplete instruments
 */
export const useListInstruments = <TData = Awaited<ReturnType<typeof listInstruments>>, TError = AxiosError<unknown>>(
 params?: ListInstrumentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listInstruments>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getListInstrumentsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Price slice for sparkline
 */
export const getInstrumentPrices = (
    symbol: string,
    params?: GetInstrumentPricesParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PriceCandle[]>> => {
    
    return axios.default.get(
      `/instruments/${symbol}/prices`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getGetInstrumentPricesQueryKey = (symbol: string,
    params?: GetInstrumentPricesParams,) => {
    return [`/instruments/${symbol}/prices`, ...(params ? [params]: [])] as const;
    }

    
export const getGetInstrumentPricesQueryOptions = <TData = Awaited<ReturnType<typeof getInstrumentPrices>>, TError = AxiosError<unknown>>(symbol: string,
    params?: GetInstrumentPricesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInstrumentPrices>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetInstrumentPricesQueryKey(symbol,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getInstrumentPrices>>> = ({ signal }) => getInstrumentPrices(symbol,params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(symbol), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getInstrumentPrices>>, TError, TData> & { queryKey: QueryKey }
}

export type GetInstrumentPricesQueryResult = NonNullable<Awaited<ReturnType<typeof getInstrumentPrices>>>
export type GetInstrumentPricesQueryError = AxiosError<unknown>

/**
 * @summary Price slice for sparkline
 */
export const useGetInstrumentPrices = <TData = Awaited<ReturnType<typeof getInstrumentPrices>>, TError = AxiosError<unknown>>(
 symbol: string,
    params?: GetInstrumentPricesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInstrumentPrices>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetInstrumentPricesQueryOptions(symbol,params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Indicator slice for chart tabs
 */
export const getInstrumentIndicators = (
    symbol: string,
    params?: GetInstrumentIndicatorsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<IndicatorPoint[]>> => {
    
    return axios.default.get(
      `/instruments/${symbol}/indicators`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getGetInstrumentIndicatorsQueryKey = (symbol: string,
    params?: GetInstrumentIndicatorsParams,) => {
    return [`/instruments/${symbol}/indicators`, ...(params ? [params]: [])] as const;
    }

    
export const getGetInstrumentIndicatorsQueryOptions = <TData = Awaited<ReturnType<typeof getInstrumentIndicators>>, TError = AxiosError<unknown>>(symbol: string,
    params?: GetInstrumentIndicatorsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInstrumentIndicators>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetInstrumentIndicatorsQueryKey(symbol,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getInstrumentIndicators>>> = ({ signal }) => getInstrumentIndicators(symbol,params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(symbol), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getInstrumentIndicators>>, TError, TData> & { queryKey: QueryKey }
}

export type GetInstrumentIndicatorsQueryResult = NonNullable<Awaited<ReturnType<typeof getInstrumentIndicators>>>
export type GetInstrumentIndicatorsQueryError = AxiosError<unknown>

/**
 * @summary Indicator slice for chart tabs
 */
export const useGetInstrumentIndicators = <TData = Awaited<ReturnType<typeof getInstrumentIndicators>>, TError = AxiosError<unknown>>(
 symbol: string,
    params?: GetInstrumentIndicatorsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInstrumentIndicators>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetInstrumentIndicatorsQueryOptions(symbol,params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary List locked positions (optional filter by symbol)
 */
export const listPositions = (
    params?: ListPositionsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PositionOut[]>> => {
    
    return axios.default.get(
      `/positions`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getListPositionsQueryKey = (params?: ListPositionsParams,) => {
    return [`/positions`, ...(params ? [params]: [])] as const;
    }

    
export const getListPositionsQueryOptions = <TData = Awaited<ReturnType<typeof listPositions>>, TError = AxiosError<unknown>>(params?: ListPositionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPositions>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListPositionsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listPositions>>> = ({ signal }) => listPositions(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listPositions>>, TError, TData> & { queryKey: QueryKey }
}

export type ListPositionsQueryResult = NonNullable<Awaited<ReturnType<typeof listPositions>>>
export type ListPositionsQueryError = AxiosError<unknown>

/**
 * @summary List locked positions (optional filter by symbol)
 */
export const useListPositions = <TData = Awaited<ReturnType<typeof listPositions>>, TError = AxiosError<unknown>>(
 params?: ListPositionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPositions>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getListPositionsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Lock price / anchor baseline
 */
export const createPosition = (
    positionIn: PositionIn, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PositionOut>> => {
    
    return axios.default.post(
      `/positions`,
      positionIn,options
    );
  }



export const getCreatePositionMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPosition>>, TError,{data: PositionIn}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createPosition>>, TError,{data: PositionIn}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createPosition>>, {data: PositionIn}> = (props) => {
          const {data} = props ?? {};

          return  createPosition(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreatePositionMutationResult = NonNullable<Awaited<ReturnType<typeof createPosition>>>
    export type CreatePositionMutationBody = PositionIn
    export type CreatePositionMutationError = AxiosError<unknown>

    /**
 * @summary Lock price / anchor baseline
 */
export const useCreatePosition = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPosition>>, TError,{data: PositionIn}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof createPosition>>,
        TError,
        {data: PositionIn},
        TContext
      > => {

      const mutationOptions = getCreatePositionMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Update note/price/date
 */
export const updatePosition = (
    id: number,
    positionIn: PositionIn, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PositionOut>> => {
    
    return axios.default.put(
      `/positions/${id}`,
      positionIn,options
    );
  }



export const getUpdatePositionMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePosition>>, TError,{id: number;data: PositionIn}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updatePosition>>, TError,{id: number;data: PositionIn}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updatePosition>>, {id: number;data: PositionIn}> = (props) => {
          const {id,data} = props ?? {};

          return  updatePosition(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdatePositionMutationResult = NonNullable<Awaited<ReturnType<typeof updatePosition>>>
    export type UpdatePositionMutationBody = PositionIn
    export type UpdatePositionMutationError = AxiosError<unknown>

    /**
 * @summary Update note/price/date
 */
export const useUpdatePosition = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePosition>>, TError,{id: number;data: PositionIn}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof updatePosition>>,
        TError,
        {id: number;data: PositionIn},
        TContext
      > => {

      const mutationOptions = getUpdatePositionMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Delete saved position for a symbol
 */
export const deletePosition = (
    symbol: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    return axios.default.delete(
      `/api/v1/positions/${symbol}`,options
    );
  }



export const getDeletePositionMutationOptions = <TError = AxiosError<Problem>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePosition>>, TError,{symbol: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deletePosition>>, TError,{symbol: string}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deletePosition>>, {symbol: string}> = (props) => {
          const {symbol} = props ?? {};

          return  deletePosition(symbol,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeletePositionMutationResult = NonNullable<Awaited<ReturnType<typeof deletePosition>>>
    
    export type DeletePositionMutationError = AxiosError<Problem>

    /**
 * @summary Delete saved position for a symbol
 */
export const useDeletePosition = <TError = AxiosError<Problem>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePosition>>, TError,{symbol: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof deletePosition>>,
        TError,
        {symbol: string},
        TContext
      > => {

      const mutationOptions = getDeletePositionMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Pin a snapshot for a symbol
 */
export const pinSnapshot = (
    snapshotPinIn: SnapshotPinIn, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SnapshotPinOut>> => {
    
    return axios.default.post(
      `/snapshots/pin`,
      snapshotPinIn,options
    );
  }



export const getPinSnapshotMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof pinSnapshot>>, TError,{data: SnapshotPinIn}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof pinSnapshot>>, TError,{data: SnapshotPinIn}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof pinSnapshot>>, {data: SnapshotPinIn}> = (props) => {
          const {data} = props ?? {};

          return  pinSnapshot(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PinSnapshotMutationResult = NonNullable<Awaited<ReturnType<typeof pinSnapshot>>>
    export type PinSnapshotMutationBody = SnapshotPinIn
    export type PinSnapshotMutationError = AxiosError<unknown>

    /**
 * @summary Pin a snapshot for a symbol
 */
export const usePinSnapshot = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof pinSnapshot>>, TError,{data: SnapshotPinIn}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof pinSnapshot>>,
        TError,
        {data: SnapshotPinIn},
        TContext
      > => {

      const mutationOptions = getPinSnapshotMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary List pins (optionally by symbol)
 */
export const listSnapshotPins = (
    params?: ListSnapshotPinsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SnapshotPinOut[]>> => {
    
    return axios.default.get(
      `/snapshots/pins`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getListSnapshotPinsQueryKey = (params?: ListSnapshotPinsParams,) => {
    return [`/snapshots/pins`, ...(params ? [params]: [])] as const;
    }

    
export const getListSnapshotPinsQueryOptions = <TData = Awaited<ReturnType<typeof listSnapshotPins>>, TError = AxiosError<unknown>>(params?: ListSnapshotPinsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSnapshotPins>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListSnapshotPinsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listSnapshotPins>>> = ({ signal }) => listSnapshotPins(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listSnapshotPins>>, TError, TData> & { queryKey: QueryKey }
}

export type ListSnapshotPinsQueryResult = NonNullable<Awaited<ReturnType<typeof listSnapshotPins>>>
export type ListSnapshotPinsQueryError = AxiosError<unknown>

/**
 * @summary List pins (optionally by symbol)
 */
export const useListSnapshotPins = <TData = Awaited<ReturnType<typeof listSnapshotPins>>, TError = AxiosError<unknown>>(
 params?: ListSnapshotPinsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSnapshotPins>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getListSnapshotPinsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Remove a pin
 */
export const unpinSnapshot = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    return axios.default.delete(
      `/snapshots/pin/${id}`,options
    );
  }



export const getUnpinSnapshotMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unpinSnapshot>>, TError,{id: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof unpinSnapshot>>, TError,{id: number}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof unpinSnapshot>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  unpinSnapshot(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UnpinSnapshotMutationResult = NonNullable<Awaited<ReturnType<typeof unpinSnapshot>>>
    
    export type UnpinSnapshotMutationError = AxiosError<unknown>

    /**
 * @summary Remove a pin
 */
export const useUnpinSnapshot = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unpinSnapshot>>, TError,{id: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof unpinSnapshot>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getUnpinSnapshotMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary List alert rules and states
 */
export const listAlerts = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AlertState[]>> => {
    
    return axios.default.get(
      `/alerts`,options
    );
  }


export const getListAlertsQueryKey = () => {
    return [`/alerts`] as const;
    }

    
export const getListAlertsQueryOptions = <TData = Awaited<ReturnType<typeof listAlerts>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAlerts>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListAlertsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAlerts>>> = ({ signal }) => listAlerts({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAlerts>>, TError, TData> & { queryKey: QueryKey }
}

export type ListAlertsQueryResult = NonNullable<Awaited<ReturnType<typeof listAlerts>>>
export type ListAlertsQueryError = AxiosError<unknown>

/**
 * @summary List alert rules and states
 */
export const useListAlerts = <TData = Awaited<ReturnType<typeof listAlerts>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAlerts>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getListAlertsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Create alert rule
 */
export const createAlert = (
    alertRule: AlertRule, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AlertState>> => {
    
    return axios.default.post(
      `/alerts`,
      alertRule,options
    );
  }



export const getCreateAlertMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createAlert>>, TError,{data: AlertRule}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createAlert>>, TError,{data: AlertRule}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createAlert>>, {data: AlertRule}> = (props) => {
          const {data} = props ?? {};

          return  createAlert(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateAlertMutationResult = NonNullable<Awaited<ReturnType<typeof createAlert>>>
    export type CreateAlertMutationBody = AlertRule
    export type CreateAlertMutationError = AxiosError<unknown>

    /**
 * @summary Create alert rule
 */
export const useCreateAlert = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createAlert>>, TError,{data: AlertRule}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof createAlert>>,
        TError,
        {data: AlertRule},
        TContext
      > => {

      const mutationOptions = getCreateAlertMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Update alert rule
 */
export const updateAlert = (
    id: number,
    alertRule: AlertRule, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AlertState>> => {
    
    return axios.default.put(
      `/alerts/${id}`,
      alertRule,options
    );
  }



export const getUpdateAlertMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateAlert>>, TError,{id: number;data: AlertRule}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateAlert>>, TError,{id: number;data: AlertRule}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateAlert>>, {id: number;data: AlertRule}> = (props) => {
          const {id,data} = props ?? {};

          return  updateAlert(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateAlertMutationResult = NonNullable<Awaited<ReturnType<typeof updateAlert>>>
    export type UpdateAlertMutationBody = AlertRule
    export type UpdateAlertMutationError = AxiosError<unknown>

    /**
 * @summary Update alert rule
 */
export const useUpdateAlert = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateAlert>>, TError,{id: number;data: AlertRule}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof updateAlert>>,
        TError,
        {id: number;data: AlertRule},
        TContext
      > => {

      const mutationOptions = getUpdateAlertMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Delete alert rule
 */
export const deleteAlert = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    return axios.default.delete(
      `/alerts/${id}`,options
    );
  }



export const getDeleteAlertMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAlert>>, TError,{id: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAlert>>, TError,{id: number}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAlert>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteAlert(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteAlertMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAlert>>>
    
    export type DeleteAlertMutationError = AxiosError<unknown>

    /**
 * @summary Delete alert rule
 */
export const useDeleteAlert = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAlert>>, TError,{id: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof deleteAlert>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteAlertMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Preview digest (no send)
 */
export const previewAlertDigest = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PreviewAlertDigest200>> => {
    
    return axios.default.get(
      `/alerts/digest`,options
    );
  }


export const getPreviewAlertDigestQueryKey = () => {
    return [`/alerts/digest`] as const;
    }

    
export const getPreviewAlertDigestQueryOptions = <TData = Awaited<ReturnType<typeof previewAlertDigest>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previewAlertDigest>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPreviewAlertDigestQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof previewAlertDigest>>> = ({ signal }) => previewAlertDigest({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof previewAlertDigest>>, TError, TData> & { queryKey: QueryKey }
}

export type PreviewAlertDigestQueryResult = NonNullable<Awaited<ReturnType<typeof previewAlertDigest>>>
export type PreviewAlertDigestQueryError = AxiosError<unknown>

/**
 * @summary Preview digest (no send)
 */
export const usePreviewAlertDigest = <TData = Awaited<ReturnType<typeof previewAlertDigest>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previewAlertDigest>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getPreviewAlertDigestQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get instrument drawer detail (backend-only)
 */
export const getInstrumentsSymbolDetail = (
    symbol: string,
    params?: GetInstrumentsSymbolDetailParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DrawerDetail>> => {
    
    return axios.default.get(
      `/instruments/${symbol}/detail`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getGetInstrumentsSymbolDetailQueryKey = (symbol: string,
    params?: GetInstrumentsSymbolDetailParams,) => {
    return [`/instruments/${symbol}/detail`, ...(params ? [params]: [])] as const;
    }

    
export const getGetInstrumentsSymbolDetailQueryOptions = <TData = Awaited<ReturnType<typeof getInstrumentsSymbolDetail>>, TError = AxiosError<unknown>>(symbol: string,
    params?: GetInstrumentsSymbolDetailParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInstrumentsSymbolDetail>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetInstrumentsSymbolDetailQueryKey(symbol,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getInstrumentsSymbolDetail>>> = ({ signal }) => getInstrumentsSymbolDetail(symbol,params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(symbol), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getInstrumentsSymbolDetail>>, TError, TData> & { queryKey: QueryKey }
}

export type GetInstrumentsSymbolDetailQueryResult = NonNullable<Awaited<ReturnType<typeof getInstrumentsSymbolDetail>>>
export type GetInstrumentsSymbolDetailQueryError = AxiosError<unknown>

/**
 * @summary Get instrument drawer detail (backend-only)
 */
export const useGetInstrumentsSymbolDetail = <TData = Awaited<ReturnType<typeof getInstrumentsSymbolDetail>>, TError = AxiosError<unknown>>(
 symbol: string,
    params?: GetInstrumentsSymbolDetailParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInstrumentsSymbolDetail>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetInstrumentsSymbolDetailQueryOptions(symbol,params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get saved position (locked drawer state) for a symbol
 */
export const getPosition = (
    symbol: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PositionOut>> => {
    
    return axios.default.get(
      `/api/v1/positions/${symbol}`,options
    );
  }


export const getGetPositionQueryKey = (symbol: string,) => {
    return [`/api/v1/positions/${symbol}`] as const;
    }

    
export const getGetPositionQueryOptions = <TData = Awaited<ReturnType<typeof getPosition>>, TError = AxiosError<Problem>>(symbol: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPosition>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPositionQueryKey(symbol);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPosition>>> = ({ signal }) => getPosition(symbol, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(symbol), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPosition>>, TError, TData> & { queryKey: QueryKey }
}

export type GetPositionQueryResult = NonNullable<Awaited<ReturnType<typeof getPosition>>>
export type GetPositionQueryError = AxiosError<Problem>

/**
 * @summary Get saved position (locked drawer state) for a symbol
 */
export const useGetPosition = <TData = Awaited<ReturnType<typeof getPosition>>, TError = AxiosError<Problem>>(
 symbol: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPosition>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetPositionQueryOptions(symbol,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Upsert endpoint. Send only fields you want to set/update. Typical flow: when user clicks **Lock Entry**, send `entry_price_locked` using the drawer’s suggested entry (`next_action.refs.entry_suggested`) with `qty` and `trade_on=true`.

 * @summary Create or update (upsert) locked drawer state for a symbol
 */
export const upsertPosition = (
    symbol: string,
    positionUpsert: PositionUpsert, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PositionOut>> => {
    
    return axios.default.put(
      `/api/v1/positions/${symbol}`,
      positionUpsert,options
    );
  }



export const getUpsertPositionMutationOptions = <TError = AxiosError<Problem>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof upsertPosition>>, TError,{symbol: string;data: PositionUpsert}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof upsertPosition>>, TError,{symbol: string;data: PositionUpsert}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof upsertPosition>>, {symbol: string;data: PositionUpsert}> = (props) => {
          const {symbol,data} = props ?? {};

          return  upsertPosition(symbol,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpsertPositionMutationResult = NonNullable<Awaited<ReturnType<typeof upsertPosition>>>
    export type UpsertPositionMutationBody = PositionUpsert
    export type UpsertPositionMutationError = AxiosError<Problem>

    /**
 * @summary Create or update (upsert) locked drawer state for a symbol
 */
export const useUpsertPosition = <TError = AxiosError<Problem>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof upsertPosition>>, TError,{symbol: string;data: PositionUpsert}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof upsertPosition>>,
        TError,
        {symbol: string;data: PositionUpsert},
        TContext
      > => {

      const mutationOptions = getUpsertPositionMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Get user watchlists & symbols
 */
export const getWatchlist = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetWatchlist200>> => {
    
    return axios.default.get(
      `/watchlist`,options
    );
  }


export const getGetWatchlistQueryKey = () => {
    return [`/watchlist`] as const;
    }

    
export const getGetWatchlistQueryOptions = <TData = Awaited<ReturnType<typeof getWatchlist>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWatchlist>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetWatchlistQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getWatchlist>>> = ({ signal }) => getWatchlist({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getWatchlist>>, TError, TData> & { queryKey: QueryKey }
}

export type GetWatchlistQueryResult = NonNullable<Awaited<ReturnType<typeof getWatchlist>>>
export type GetWatchlistQueryError = AxiosError<unknown>

/**
 * @summary Get user watchlists & symbols
 */
export const useGetWatchlist = <TData = Awaited<ReturnType<typeof getWatchlist>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWatchlist>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetWatchlistQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Add symbols (optionally create list)
 */
export const addToWatchlist = (
    addToWatchlistBody: AddToWatchlistBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    return axios.default.post(
      `/watchlist`,
      addToWatchlistBody,options
    );
  }



export const getAddToWatchlistMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addToWatchlist>>, TError,{data: AddToWatchlistBody}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof addToWatchlist>>, TError,{data: AddToWatchlistBody}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addToWatchlist>>, {data: AddToWatchlistBody}> = (props) => {
          const {data} = props ?? {};

          return  addToWatchlist(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AddToWatchlistMutationResult = NonNullable<Awaited<ReturnType<typeof addToWatchlist>>>
    export type AddToWatchlistMutationBody = AddToWatchlistBody
    export type AddToWatchlistMutationError = AxiosError<unknown>

    /**
 * @summary Add symbols (optionally create list)
 */
export const useAddToWatchlist = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addToWatchlist>>, TError,{data: AddToWatchlistBody}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof addToWatchlist>>,
        TError,
        {data: AddToWatchlistBody},
        TContext
      > => {

      const mutationOptions = getAddToWatchlistMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Remove symbol from default or named list
 */
export const removeFromWatchlist = (
    symbol: string,
    params?: RemoveFromWatchlistParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    return axios.default.delete(
      `/watchlist/${symbol}`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getRemoveFromWatchlistMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeFromWatchlist>>, TError,{symbol: string;params?: RemoveFromWatchlistParams}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof removeFromWatchlist>>, TError,{symbol: string;params?: RemoveFromWatchlistParams}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof removeFromWatchlist>>, {symbol: string;params?: RemoveFromWatchlistParams}> = (props) => {
          const {symbol,params} = props ?? {};

          return  removeFromWatchlist(symbol,params,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RemoveFromWatchlistMutationResult = NonNullable<Awaited<ReturnType<typeof removeFromWatchlist>>>
    
    export type RemoveFromWatchlistMutationError = AxiosError<unknown>

    /**
 * @summary Remove symbol from default or named list
 */
export const useRemoveFromWatchlist = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeFromWatchlist>>, TError,{symbol: string;params?: RemoveFromWatchlistParams}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof removeFromWatchlist>>,
        TError,
        {symbol: string;params?: RemoveFromWatchlistParams},
        TContext
      > => {

      const mutationOptions = getRemoveFromWatchlistMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Historical outcomes (linked to run_id)
 */
export const listHistory = (
    params?: ListHistoryParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<HistoryRow[]>> => {
    
    return axios.default.get(
      `/history`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getListHistoryQueryKey = (params?: ListHistoryParams,) => {
    return [`/history`, ...(params ? [params]: [])] as const;
    }

    
export const getListHistoryQueryOptions = <TData = Awaited<ReturnType<typeof listHistory>>, TError = AxiosError<unknown>>(params?: ListHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listHistory>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListHistoryQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listHistory>>> = ({ signal }) => listHistory(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listHistory>>, TError, TData> & { queryKey: QueryKey }
}

export type ListHistoryQueryResult = NonNullable<Awaited<ReturnType<typeof listHistory>>>
export type ListHistoryQueryError = AxiosError<unknown>

/**
 * @summary Historical outcomes (linked to run_id)
 */
export const useListHistory = <TData = Awaited<ReturnType<typeof listHistory>>, TError = AxiosError<unknown>>(
 params?: ListHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listHistory>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getListHistoryQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Read redacted YAML-backed settings
 */
export const getSettings = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Settings>> => {
    
    return axios.default.get(
      `/settings`,options
    );
  }


export const getGetSettingsQueryKey = () => {
    return [`/settings`] as const;
    }

    
export const getGetSettingsQueryOptions = <TData = Awaited<ReturnType<typeof getSettings>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSettings>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSettingsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSettings>>> = ({ signal }) => getSettings({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSettings>>, TError, TData> & { queryKey: QueryKey }
}

export type GetSettingsQueryResult = NonNullable<Awaited<ReturnType<typeof getSettings>>>
export type GetSettingsQueryError = AxiosError<unknown>

/**
 * @summary Read redacted YAML-backed settings
 */
export const useGetSettings = <TData = Awaited<ReturnType<typeof getSettings>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSettings>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetSettingsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Update settings (validated)
 */
export const putSettings = (
    settings: Settings, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Settings>> => {
    
    return axios.default.put(
      `/settings`,
      settings,options
    );
  }



export const getPutSettingsMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putSettings>>, TError,{data: Settings}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof putSettings>>, TError,{data: Settings}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putSettings>>, {data: Settings}> = (props) => {
          const {data} = props ?? {};

          return  putSettings(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutSettingsMutationResult = NonNullable<Awaited<ReturnType<typeof putSettings>>>
    export type PutSettingsMutationBody = Settings
    export type PutSettingsMutationError = AxiosError<unknown>

    /**
 * @summary Update settings (validated)
 */
export const usePutSettings = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putSettings>>, TError,{data: Settings}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof putSettings>>,
        TError,
        {data: Settings},
        TContext
      > => {

      const mutationOptions = getPutSettingsMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Static learning content
 */
export const getLearning = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetLearning200>> => {
    
    return axios.default.get(
      `/learning`,options
    );
  }


export const getGetLearningQueryKey = () => {
    return [`/learning`] as const;
    }

    
export const getGetLearningQueryOptions = <TData = Awaited<ReturnType<typeof getLearning>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLearning>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLearningQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLearning>>> = ({ signal }) => getLearning({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLearning>>, TError, TData> & { queryKey: QueryKey }
}

export type GetLearningQueryResult = NonNullable<Awaited<ReturnType<typeof getLearning>>>
export type GetLearningQueryError = AxiosError<unknown>

/**
 * @summary Static learning content
 */
export const useGetLearning = <TData = Awaited<ReturnType<typeof getLearning>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLearning>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetLearningQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




