/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Momentum Dashboard API
 * Contract-first spec. Clients must be generated from this file. All endpoints are local-only and authenticated as N/A for now.
 * OpenAPI spec version: 0.7.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  AddToWatchlistBody,
  AlertRule,
  AlertState,
  DrawerDetail,
  GetApiV1InstrumentsSymbolDetailParams,
  GetApiV1PositionsParams,
  GetApiV1ScreenerParams,
  GetInstrumentIndicatorsParams,
  GetInstrumentPricesParams,
  GetLearning200,
  GetTopMoversParams,
  GetWatchlist200,
  HealthState,
  HistoryRow,
  IndicatorPoint,
  ListAllNewsParams,
  ListHistoryParams,
  ListInstruments200,
  ListInstrumentsParams,
  ListNewsBySymbolParams,
  ListRuns200,
  ListRunsParams,
  ListSnapshotPinsParams,
  ListUniverse200,
  ListUniverseParams,
  NewsIngestBatch,
  NewsListResponse,
  NewsMoveAttributionResponse,
  NewsWindowListResponse,
  PositionCreate,
  PositionOut,
  PositionUpdate,
  PreviewAlertDigest200,
  PriceCandle,
  Problem,
  ReasonForMoveParams,
  RemoveFromWatchlistParams,
  RunDetail,
  RunId,
  ScanRequest,
  ScreenerList,
  SectorFacet,
  Settings,
  SnapshotPinIn,
  SnapshotPinOut,
  TopMovers
} from './types'




/**
 * @summary Quick health (combined)
 */
export const health = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<HealthState>> => {
    
    return axios.default.get(
      `/api/v1/health`,options
    );
  }


export const getHealthQueryKey = () => {
    return [`/api/v1/health`] as const;
    }

    
export const getHealthQueryOptions = <TData = Awaited<ReturnType<typeof health>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof health>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof health>>> = ({ signal }) => health({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof health>>, TError, TData> & { queryKey: QueryKey }
}

export type HealthQueryResult = NonNullable<Awaited<ReturnType<typeof health>>>
export type HealthQueryError = AxiosError<unknown>

/**
 * @summary Quick health (combined)
 */
export const useHealth = <TData = Awaited<ReturnType<typeof health>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof health>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getHealthQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Liveness probe
 */
export const healthLive = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    return axios.default.get(
      `/api/v1/health/live`,options
    );
  }


export const getHealthLiveQueryKey = () => {
    return [`/api/v1/health/live`] as const;
    }

    
export const getHealthLiveQueryOptions = <TData = Awaited<ReturnType<typeof healthLive>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthLive>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthLiveQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthLive>>> = ({ signal }) => healthLive({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthLive>>, TError, TData> & { queryKey: QueryKey }
}

export type HealthLiveQueryResult = NonNullable<Awaited<ReturnType<typeof healthLive>>>
export type HealthLiveQueryError = AxiosError<unknown>

/**
 * @summary Liveness probe
 */
export const useHealthLive = <TData = Awaited<ReturnType<typeof healthLive>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthLive>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getHealthLiveQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Readiness probe (SQLite + Parquet availability)
 */
export const healthReady = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    return axios.default.get(
      `/api/v1/health/ready`,options
    );
  }


export const getHealthReadyQueryKey = () => {
    return [`/api/v1/health/ready`] as const;
    }

    
export const getHealthReadyQueryOptions = <TData = Awaited<ReturnType<typeof healthReady>>, TError = AxiosError<Problem>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthReady>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthReadyQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthReady>>> = ({ signal }) => healthReady({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthReady>>, TError, TData> & { queryKey: QueryKey }
}

export type HealthReadyQueryResult = NonNullable<Awaited<ReturnType<typeof healthReady>>>
export type HealthReadyQueryError = AxiosError<Problem>

/**
 * @summary Readiness probe (SQLite + Parquet availability)
 */
export const useHealthReady = <TData = Awaited<ReturnType<typeof healthReady>>, TError = AxiosError<Problem>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthReady>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getHealthReadyQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Prometheus metrics (optional)
 */
export const metrics = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<string>> => {
    
    return axios.default.get(
      `/api/v1/health/metrics`,options
    );
  }


export const getMetricsQueryKey = () => {
    return [`/api/v1/health/metrics`] as const;
    }

    
export const getMetricsQueryOptions = <TData = Awaited<ReturnType<typeof metrics>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof metrics>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getMetricsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof metrics>>> = ({ signal }) => metrics({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof metrics>>, TError, TData> & { queryKey: QueryKey }
}

export type MetricsQueryResult = NonNullable<Awaited<ReturnType<typeof metrics>>>
export type MetricsQueryError = AxiosError<unknown>

/**
 * @summary Prometheus metrics (optional)
 */
export const useMetrics = <TData = Awaited<ReturnType<typeof metrics>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof metrics>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getMetricsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary List screener rows (filtered, sorted, paginated)
 */
export const getApiV1Screener = (
    params?: GetApiV1ScreenerParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ScreenerList>> => {
    
    return axios.default.get(
      `/api/v1/screener`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getGetApiV1ScreenerQueryKey = (params?: GetApiV1ScreenerParams,) => {
    return [`/api/v1/screener`, ...(params ? [params]: [])] as const;
    }

    
export const getGetApiV1ScreenerQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1Screener>>, TError = AxiosError<unknown>>(params?: GetApiV1ScreenerParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Screener>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1ScreenerQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1Screener>>> = ({ signal }) => getApiV1Screener(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1Screener>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiV1ScreenerQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1Screener>>>
export type GetApiV1ScreenerQueryError = AxiosError<unknown>

/**
 * @summary List screener rows (filtered, sorted, paginated)
 */
export const useGetApiV1Screener = <TData = Awaited<ReturnType<typeof getApiV1Screener>>, TError = AxiosError<unknown>>(
 params?: GetApiV1ScreenerParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Screener>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetApiV1ScreenerQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Top gainers and losers for the requested period
 */
export const getTopMovers = (
    params?: GetTopMoversParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TopMovers>> => {
    
    return axios.default.get(
      `/api/v1/screener/top-movers`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getGetTopMoversQueryKey = (params?: GetTopMoversParams,) => {
    return [`/api/v1/screener/top-movers`, ...(params ? [params]: [])] as const;
    }

    
export const getGetTopMoversQueryOptions = <TData = Awaited<ReturnType<typeof getTopMovers>>, TError = AxiosError<unknown>>(params?: GetTopMoversParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTopMovers>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTopMoversQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTopMovers>>> = ({ signal }) => getTopMovers(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTopMovers>>, TError, TData> & { queryKey: QueryKey }
}

export type GetTopMoversQueryResult = NonNullable<Awaited<ReturnType<typeof getTopMovers>>>
export type GetTopMoversQueryError = AxiosError<unknown>

/**
 * @summary Top gainers and losers for the requested period
 */
export const useGetTopMovers = <TData = Awaited<ReturnType<typeof getTopMovers>>, TError = AxiosError<unknown>>(
 params?: GetTopMoversParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTopMovers>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetTopMoversQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Triggers a new scores snapshot with a fresh run_id. If the same
Idempotency-Key (or ScanRequest.key) is reused, returns the existing run.
On first creation: 201 Created. On idempotent replay: 200 OK.

 * @summary Start a manual screening run (idempotent)
 */
export const postScan = (
    scanRequest?: ScanRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<RunDetail>> => {
    
    return axios.default.post(
      `/api/v1/scan`,
      scanRequest,options
    );
  }



export const getPostScanMutationOptions = <TError = AxiosError<Problem | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postScan>>, TError,{data: ScanRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postScan>>, TError,{data: ScanRequest}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postScan>>, {data: ScanRequest}> = (props) => {
          const {data} = props ?? {};

          return  postScan(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostScanMutationResult = NonNullable<Awaited<ReturnType<typeof postScan>>>
    export type PostScanMutationBody = ScanRequest
    export type PostScanMutationError = AxiosError<Problem | void>

    /**
 * @summary Start a manual screening run (idempotent)
 */
export const usePostScan = <TError = AxiosError<Problem | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postScan>>, TError,{data: ScanRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof postScan>>,
        TError,
        {data: ScanRequest},
        TContext
      > => {

      const mutationOptions = getPostScanMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary List recent scan runs
 */
export const listRuns = (
    params?: ListRunsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ListRuns200>> => {
    
    return axios.default.get(
      `/api/v1/runs`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getListRunsQueryKey = (params?: ListRunsParams,) => {
    return [`/api/v1/runs`, ...(params ? [params]: [])] as const;
    }

    
export const getListRunsQueryOptions = <TData = Awaited<ReturnType<typeof listRuns>>, TError = AxiosError<unknown>>(params?: ListRunsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRuns>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListRunsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listRuns>>> = ({ signal }) => listRuns(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listRuns>>, TError, TData> & { queryKey: QueryKey }
}

export type ListRunsQueryResult = NonNullable<Awaited<ReturnType<typeof listRuns>>>
export type ListRunsQueryError = AxiosError<unknown>

/**
 * @summary List recent scan runs
 */
export const useListRuns = <TData = Awaited<ReturnType<typeof listRuns>>, TError = AxiosError<unknown>>(
 params?: ListRunsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRuns>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getListRunsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Run details
 */
export const getRun = (
    runId: RunId, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<RunDetail>> => {
    
    return axios.default.get(
      `/api/v1/runs/${runId}`,options
    );
  }


export const getGetRunQueryKey = (runId: RunId,) => {
    return [`/api/v1/runs/${runId}`] as const;
    }

    
export const getGetRunQueryOptions = <TData = Awaited<ReturnType<typeof getRun>>, TError = AxiosError<Problem>>(runId: RunId, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRun>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRunQueryKey(runId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRun>>> = ({ signal }) => getRun(runId, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(runId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRun>>, TError, TData> & { queryKey: QueryKey }
}

export type GetRunQueryResult = NonNullable<Awaited<ReturnType<typeof getRun>>>
export type GetRunQueryError = AxiosError<Problem>

/**
 * @summary Run details
 */
export const useGetRun = <TData = Awaited<ReturnType<typeof getRun>>, TError = AxiosError<Problem>>(
 runId: RunId, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRun>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetRunQueryOptions(runId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary List/search universe (symbols)
 */
export const listUniverse = (
    params?: ListUniverseParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ListUniverse200>> => {
    
    return axios.default.get(
      `/api/v1/universe`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getListUniverseQueryKey = (params?: ListUniverseParams,) => {
    return [`/api/v1/universe`, ...(params ? [params]: [])] as const;
    }

    
export const getListUniverseQueryOptions = <TData = Awaited<ReturnType<typeof listUniverse>>, TError = AxiosError<void>>(params?: ListUniverseParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUniverse>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListUniverseQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listUniverse>>> = ({ signal }) => listUniverse(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listUniverse>>, TError, TData> & { queryKey: QueryKey }
}

export type ListUniverseQueryResult = NonNullable<Awaited<ReturnType<typeof listUniverse>>>
export type ListUniverseQueryError = AxiosError<void>

/**
 * @summary List/search universe (symbols)
 */
export const useListUniverse = <TData = Awaited<ReturnType<typeof listUniverse>>, TError = AxiosError<void>>(
 params?: ListUniverseParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUniverse>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getListUniverseQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Sector facets with counts
 */
export const listSectors = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SectorFacet[]>> => {
    
    return axios.default.get(
      `/api/v1/universe/sectors`,options
    );
  }


export const getListSectorsQueryKey = () => {
    return [`/api/v1/universe/sectors`] as const;
    }

    
export const getListSectorsQueryOptions = <TData = Awaited<ReturnType<typeof listSectors>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSectors>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListSectorsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listSectors>>> = ({ signal }) => listSectors({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listSectors>>, TError, TData> & { queryKey: QueryKey }
}

export type ListSectorsQueryResult = NonNullable<Awaited<ReturnType<typeof listSectors>>>
export type ListSectorsQueryError = AxiosError<unknown>

/**
 * @summary Sector facets with counts
 */
export const useListSectors = <TData = Awaited<ReturnType<typeof listSectors>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSectors>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getListSectorsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Search/autocomplete instruments
 */
export const listInstruments = (
    params?: ListInstrumentsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ListInstruments200>> => {
    
    return axios.default.get(
      `/api/v1/instruments`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getListInstrumentsQueryKey = (params?: ListInstrumentsParams,) => {
    return [`/api/v1/instruments`, ...(params ? [params]: [])] as const;
    }

    
export const getListInstrumentsQueryOptions = <TData = Awaited<ReturnType<typeof listInstruments>>, TError = AxiosError<unknown>>(params?: ListInstrumentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listInstruments>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListInstrumentsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listInstruments>>> = ({ signal }) => listInstruments(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listInstruments>>, TError, TData> & { queryKey: QueryKey }
}

export type ListInstrumentsQueryResult = NonNullable<Awaited<ReturnType<typeof listInstruments>>>
export type ListInstrumentsQueryError = AxiosError<unknown>

/**
 * @summary Search/autocomplete instruments
 */
export const useListInstruments = <TData = Awaited<ReturnType<typeof listInstruments>>, TError = AxiosError<unknown>>(
 params?: ListInstrumentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listInstruments>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getListInstrumentsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Price slice for sparkline
 */
export const getInstrumentPrices = (
    symbol: string,
    params?: GetInstrumentPricesParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PriceCandle[]>> => {
    
    return axios.default.get(
      `/api/v1/instruments/${symbol}/prices`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getGetInstrumentPricesQueryKey = (symbol: string,
    params?: GetInstrumentPricesParams,) => {
    return [`/api/v1/instruments/${symbol}/prices`, ...(params ? [params]: [])] as const;
    }

    
export const getGetInstrumentPricesQueryOptions = <TData = Awaited<ReturnType<typeof getInstrumentPrices>>, TError = AxiosError<unknown>>(symbol: string,
    params?: GetInstrumentPricesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInstrumentPrices>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetInstrumentPricesQueryKey(symbol,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getInstrumentPrices>>> = ({ signal }) => getInstrumentPrices(symbol,params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(symbol), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getInstrumentPrices>>, TError, TData> & { queryKey: QueryKey }
}

export type GetInstrumentPricesQueryResult = NonNullable<Awaited<ReturnType<typeof getInstrumentPrices>>>
export type GetInstrumentPricesQueryError = AxiosError<unknown>

/**
 * @summary Price slice for sparkline
 */
export const useGetInstrumentPrices = <TData = Awaited<ReturnType<typeof getInstrumentPrices>>, TError = AxiosError<unknown>>(
 symbol: string,
    params?: GetInstrumentPricesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInstrumentPrices>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetInstrumentPricesQueryOptions(symbol,params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Indicator slice for chart tabs
 */
export const getInstrumentIndicators = (
    symbol: string,
    params?: GetInstrumentIndicatorsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<IndicatorPoint[]>> => {
    
    return axios.default.get(
      `/api/v1/instruments/${symbol}/indicators`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getGetInstrumentIndicatorsQueryKey = (symbol: string,
    params?: GetInstrumentIndicatorsParams,) => {
    return [`/api/v1/instruments/${symbol}/indicators`, ...(params ? [params]: [])] as const;
    }

    
export const getGetInstrumentIndicatorsQueryOptions = <TData = Awaited<ReturnType<typeof getInstrumentIndicators>>, TError = AxiosError<unknown>>(symbol: string,
    params?: GetInstrumentIndicatorsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInstrumentIndicators>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetInstrumentIndicatorsQueryKey(symbol,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getInstrumentIndicators>>> = ({ signal }) => getInstrumentIndicators(symbol,params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(symbol), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getInstrumentIndicators>>, TError, TData> & { queryKey: QueryKey }
}

export type GetInstrumentIndicatorsQueryResult = NonNullable<Awaited<ReturnType<typeof getInstrumentIndicators>>>
export type GetInstrumentIndicatorsQueryError = AxiosError<unknown>

/**
 * @summary Indicator slice for chart tabs
 */
export const useGetInstrumentIndicators = <TData = Awaited<ReturnType<typeof getInstrumentIndicators>>, TError = AxiosError<unknown>>(
 symbol: string,
    params?: GetInstrumentIndicatorsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInstrumentIndicators>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetInstrumentIndicatorsQueryOptions(symbol,params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary List positions (optionally filter by symbol/status)
 */
export const getApiV1Positions = (
    params?: GetApiV1PositionsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PositionOut[]>> => {
    
    return axios.default.get(
      `/api/v1/positions`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getGetApiV1PositionsQueryKey = (params?: GetApiV1PositionsParams,) => {
    return [`/api/v1/positions`, ...(params ? [params]: [])] as const;
    }

    
export const getGetApiV1PositionsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1Positions>>, TError = AxiosError<unknown>>(params?: GetApiV1PositionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Positions>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1PositionsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1Positions>>> = ({ signal }) => getApiV1Positions(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1Positions>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiV1PositionsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1Positions>>>
export type GetApiV1PositionsQueryError = AxiosError<unknown>

/**
 * @summary List positions (optionally filter by symbol/status)
 */
export const useGetApiV1Positions = <TData = Awaited<ReturnType<typeof getApiV1Positions>>, TError = AxiosError<unknown>>(
 params?: GetApiV1PositionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Positions>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetApiV1PositionsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Lock a position (create-or-lock)
 */
export const postApiV1Positions = (
    positionCreate: PositionCreate, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PositionOut>> => {
    
    return axios.default.post(
      `/api/v1/positions`,
      positionCreate,options
    );
  }



export const getPostApiV1PositionsMutationOptions = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1Positions>>, TError,{data: PositionCreate}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1Positions>>, TError,{data: PositionCreate}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1Positions>>, {data: PositionCreate}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1Positions(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1PositionsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1Positions>>>
    export type PostApiV1PositionsMutationBody = PositionCreate
    export type PostApiV1PositionsMutationError = AxiosError<void>

    /**
 * @summary Lock a position (create-or-lock)
 */
export const usePostApiV1Positions = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1Positions>>, TError,{data: PositionCreate}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1Positions>>,
        TError,
        {data: PositionCreate},
        TContext
      > => {

      const mutationOptions = getPostApiV1PositionsMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Get a position by symbol
 */
export const getApiV1PositionsSymbol = (
    symbol: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PositionOut>> => {
    
    return axios.default.get(
      `/api/v1/positions/${symbol}`,options
    );
  }


export const getGetApiV1PositionsSymbolQueryKey = (symbol: string,) => {
    return [`/api/v1/positions/${symbol}`] as const;
    }

    
export const getGetApiV1PositionsSymbolQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1PositionsSymbol>>, TError = AxiosError<void>>(symbol: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PositionsSymbol>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1PositionsSymbolQueryKey(symbol);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1PositionsSymbol>>> = ({ signal }) => getApiV1PositionsSymbol(symbol, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(symbol), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1PositionsSymbol>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiV1PositionsSymbolQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1PositionsSymbol>>>
export type GetApiV1PositionsSymbolQueryError = AxiosError<void>

/**
 * @summary Get a position by symbol
 */
export const useGetApiV1PositionsSymbol = <TData = Awaited<ReturnType<typeof getApiV1PositionsSymbol>>, TError = AxiosError<void>>(
 symbol: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PositionsSymbol>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetApiV1PositionsSymbolQueryOptions(symbol,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Update mutable fields of a position (including close)
 */
export const putApiV1PositionsId = (
    id: number,
    positionUpdate: PositionUpdate, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PositionOut>> => {
    
    return axios.default.put(
      `/api/v1/positions/${id}`,
      positionUpdate,options
    );
  }



export const getPutApiV1PositionsIdMutationOptions = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV1PositionsId>>, TError,{id: number;data: PositionUpdate}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof putApiV1PositionsId>>, TError,{id: number;data: PositionUpdate}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiV1PositionsId>>, {id: number;data: PositionUpdate}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiV1PositionsId(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiV1PositionsIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiV1PositionsId>>>
    export type PutApiV1PositionsIdMutationBody = PositionUpdate
    export type PutApiV1PositionsIdMutationError = AxiosError<void>

    /**
 * @summary Update mutable fields of a position (including close)
 */
export const usePutApiV1PositionsId = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV1PositionsId>>, TError,{id: number;data: PositionUpdate}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof putApiV1PositionsId>>,
        TError,
        {id: number;data: PositionUpdate},
        TContext
      > => {

      const mutationOptions = getPutApiV1PositionsIdMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Soft-close a position (legacy delete)
 */
export const deleteApiV1PositionsId = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    return axios.default.delete(
      `/api/v1/positions/${id}`,options
    );
  }



export const getDeleteApiV1PositionsIdMutationOptions = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1PositionsId>>, TError,{id: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1PositionsId>>, TError,{id: number}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV1PositionsId>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiV1PositionsId(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV1PositionsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV1PositionsId>>>
    
    export type DeleteApiV1PositionsIdMutationError = AxiosError<void>

    /**
 * @summary Soft-close a position (legacy delete)
 */
export const useDeleteApiV1PositionsId = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1PositionsId>>, TError,{id: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV1PositionsId>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteApiV1PositionsIdMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Pin a snapshot for a symbol
 */
export const pinSnapshot = (
    snapshotPinIn: SnapshotPinIn, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SnapshotPinOut>> => {
    
    return axios.default.post(
      `/api/v1/snapshots/pin`,
      snapshotPinIn,options
    );
  }



export const getPinSnapshotMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof pinSnapshot>>, TError,{data: SnapshotPinIn}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof pinSnapshot>>, TError,{data: SnapshotPinIn}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof pinSnapshot>>, {data: SnapshotPinIn}> = (props) => {
          const {data} = props ?? {};

          return  pinSnapshot(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PinSnapshotMutationResult = NonNullable<Awaited<ReturnType<typeof pinSnapshot>>>
    export type PinSnapshotMutationBody = SnapshotPinIn
    export type PinSnapshotMutationError = AxiosError<unknown>

    /**
 * @summary Pin a snapshot for a symbol
 */
export const usePinSnapshot = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof pinSnapshot>>, TError,{data: SnapshotPinIn}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof pinSnapshot>>,
        TError,
        {data: SnapshotPinIn},
        TContext
      > => {

      const mutationOptions = getPinSnapshotMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary List pins (optionally by symbol)
 */
export const listSnapshotPins = (
    params?: ListSnapshotPinsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SnapshotPinOut[]>> => {
    
    return axios.default.get(
      `/api/v1/snapshots/pins`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getListSnapshotPinsQueryKey = (params?: ListSnapshotPinsParams,) => {
    return [`/api/v1/snapshots/pins`, ...(params ? [params]: [])] as const;
    }

    
export const getListSnapshotPinsQueryOptions = <TData = Awaited<ReturnType<typeof listSnapshotPins>>, TError = AxiosError<unknown>>(params?: ListSnapshotPinsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSnapshotPins>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListSnapshotPinsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listSnapshotPins>>> = ({ signal }) => listSnapshotPins(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listSnapshotPins>>, TError, TData> & { queryKey: QueryKey }
}

export type ListSnapshotPinsQueryResult = NonNullable<Awaited<ReturnType<typeof listSnapshotPins>>>
export type ListSnapshotPinsQueryError = AxiosError<unknown>

/**
 * @summary List pins (optionally by symbol)
 */
export const useListSnapshotPins = <TData = Awaited<ReturnType<typeof listSnapshotPins>>, TError = AxiosError<unknown>>(
 params?: ListSnapshotPinsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSnapshotPins>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getListSnapshotPinsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Remove a pin
 */
export const unpinSnapshot = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    return axios.default.delete(
      `/api/v1/snapshots/pin/${id}`,options
    );
  }



export const getUnpinSnapshotMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unpinSnapshot>>, TError,{id: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof unpinSnapshot>>, TError,{id: number}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof unpinSnapshot>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  unpinSnapshot(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UnpinSnapshotMutationResult = NonNullable<Awaited<ReturnType<typeof unpinSnapshot>>>
    
    export type UnpinSnapshotMutationError = AxiosError<unknown>

    /**
 * @summary Remove a pin
 */
export const useUnpinSnapshot = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unpinSnapshot>>, TError,{id: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof unpinSnapshot>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getUnpinSnapshotMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary List alert rules and states
 */
export const listAlerts = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AlertState[]>> => {
    
    return axios.default.get(
      `/api/v1/alerts`,options
    );
  }


export const getListAlertsQueryKey = () => {
    return [`/api/v1/alerts`] as const;
    }

    
export const getListAlertsQueryOptions = <TData = Awaited<ReturnType<typeof listAlerts>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAlerts>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListAlertsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAlerts>>> = ({ signal }) => listAlerts({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAlerts>>, TError, TData> & { queryKey: QueryKey }
}

export type ListAlertsQueryResult = NonNullable<Awaited<ReturnType<typeof listAlerts>>>
export type ListAlertsQueryError = AxiosError<unknown>

/**
 * @summary List alert rules and states
 */
export const useListAlerts = <TData = Awaited<ReturnType<typeof listAlerts>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAlerts>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getListAlertsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Create alert rule
 */
export const createAlert = (
    alertRule: AlertRule, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AlertState>> => {
    
    return axios.default.post(
      `/api/v1/alerts`,
      alertRule,options
    );
  }



export const getCreateAlertMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createAlert>>, TError,{data: AlertRule}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createAlert>>, TError,{data: AlertRule}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createAlert>>, {data: AlertRule}> = (props) => {
          const {data} = props ?? {};

          return  createAlert(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateAlertMutationResult = NonNullable<Awaited<ReturnType<typeof createAlert>>>
    export type CreateAlertMutationBody = AlertRule
    export type CreateAlertMutationError = AxiosError<unknown>

    /**
 * @summary Create alert rule
 */
export const useCreateAlert = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createAlert>>, TError,{data: AlertRule}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof createAlert>>,
        TError,
        {data: AlertRule},
        TContext
      > => {

      const mutationOptions = getCreateAlertMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Update alert rule
 */
export const updateAlert = (
    id: number,
    alertRule: AlertRule, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AlertState>> => {
    
    return axios.default.put(
      `/api/v1/alerts/${id}`,
      alertRule,options
    );
  }



export const getUpdateAlertMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateAlert>>, TError,{id: number;data: AlertRule}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateAlert>>, TError,{id: number;data: AlertRule}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateAlert>>, {id: number;data: AlertRule}> = (props) => {
          const {id,data} = props ?? {};

          return  updateAlert(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateAlertMutationResult = NonNullable<Awaited<ReturnType<typeof updateAlert>>>
    export type UpdateAlertMutationBody = AlertRule
    export type UpdateAlertMutationError = AxiosError<unknown>

    /**
 * @summary Update alert rule
 */
export const useUpdateAlert = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateAlert>>, TError,{id: number;data: AlertRule}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof updateAlert>>,
        TError,
        {id: number;data: AlertRule},
        TContext
      > => {

      const mutationOptions = getUpdateAlertMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Delete alert rule
 */
export const deleteAlert = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    return axios.default.delete(
      `/api/v1/alerts/${id}`,options
    );
  }



export const getDeleteAlertMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAlert>>, TError,{id: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAlert>>, TError,{id: number}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAlert>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteAlert(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteAlertMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAlert>>>
    
    export type DeleteAlertMutationError = AxiosError<unknown>

    /**
 * @summary Delete alert rule
 */
export const useDeleteAlert = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAlert>>, TError,{id: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof deleteAlert>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteAlertMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Preview digest (no send)
 */
export const previewAlertDigest = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PreviewAlertDigest200>> => {
    
    return axios.default.get(
      `/api/v1/alerts/digest`,options
    );
  }


export const getPreviewAlertDigestQueryKey = () => {
    return [`/api/v1/alerts/digest`] as const;
    }

    
export const getPreviewAlertDigestQueryOptions = <TData = Awaited<ReturnType<typeof previewAlertDigest>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previewAlertDigest>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPreviewAlertDigestQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof previewAlertDigest>>> = ({ signal }) => previewAlertDigest({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof previewAlertDigest>>, TError, TData> & { queryKey: QueryKey }
}

export type PreviewAlertDigestQueryResult = NonNullable<Awaited<ReturnType<typeof previewAlertDigest>>>
export type PreviewAlertDigestQueryError = AxiosError<unknown>

/**
 * @summary Preview digest (no send)
 */
export const usePreviewAlertDigest = <TData = Awaited<ReturnType<typeof previewAlertDigest>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previewAlertDigest>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getPreviewAlertDigestQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get instrument drawer detail (backend-only)
 */
export const getApiV1InstrumentsSymbolDetail = (
    symbol: string,
    params?: GetApiV1InstrumentsSymbolDetailParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DrawerDetail>> => {
    
    return axios.default.get(
      `/api/v1/instruments/${symbol}/detail`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getGetApiV1InstrumentsSymbolDetailQueryKey = (symbol: string,
    params?: GetApiV1InstrumentsSymbolDetailParams,) => {
    return [`/api/v1/instruments/${symbol}/detail`, ...(params ? [params]: [])] as const;
    }

    
export const getGetApiV1InstrumentsSymbolDetailQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1InstrumentsSymbolDetail>>, TError = AxiosError<unknown>>(symbol: string,
    params?: GetApiV1InstrumentsSymbolDetailParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1InstrumentsSymbolDetail>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1InstrumentsSymbolDetailQueryKey(symbol,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1InstrumentsSymbolDetail>>> = ({ signal }) => getApiV1InstrumentsSymbolDetail(symbol,params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(symbol), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1InstrumentsSymbolDetail>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiV1InstrumentsSymbolDetailQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1InstrumentsSymbolDetail>>>
export type GetApiV1InstrumentsSymbolDetailQueryError = AxiosError<unknown>

/**
 * @summary Get instrument drawer detail (backend-only)
 */
export const useGetApiV1InstrumentsSymbolDetail = <TData = Awaited<ReturnType<typeof getApiV1InstrumentsSymbolDetail>>, TError = AxiosError<unknown>>(
 symbol: string,
    params?: GetApiV1InstrumentsSymbolDetailParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1InstrumentsSymbolDetail>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetApiV1InstrumentsSymbolDetailQueryOptions(symbol,params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get user watchlists & symbols
 */
export const getWatchlist = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetWatchlist200>> => {
    
    return axios.default.get(
      `/api/v1/watchlist`,options
    );
  }


export const getGetWatchlistQueryKey = () => {
    return [`/api/v1/watchlist`] as const;
    }

    
export const getGetWatchlistQueryOptions = <TData = Awaited<ReturnType<typeof getWatchlist>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWatchlist>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetWatchlistQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getWatchlist>>> = ({ signal }) => getWatchlist({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getWatchlist>>, TError, TData> & { queryKey: QueryKey }
}

export type GetWatchlistQueryResult = NonNullable<Awaited<ReturnType<typeof getWatchlist>>>
export type GetWatchlistQueryError = AxiosError<unknown>

/**
 * @summary Get user watchlists & symbols
 */
export const useGetWatchlist = <TData = Awaited<ReturnType<typeof getWatchlist>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWatchlist>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetWatchlistQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Add symbols (optionally create list)
 */
export const addToWatchlist = (
    addToWatchlistBody: AddToWatchlistBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    return axios.default.post(
      `/api/v1/watchlist`,
      addToWatchlistBody,options
    );
  }



export const getAddToWatchlistMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addToWatchlist>>, TError,{data: AddToWatchlistBody}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof addToWatchlist>>, TError,{data: AddToWatchlistBody}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addToWatchlist>>, {data: AddToWatchlistBody}> = (props) => {
          const {data} = props ?? {};

          return  addToWatchlist(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AddToWatchlistMutationResult = NonNullable<Awaited<ReturnType<typeof addToWatchlist>>>
    export type AddToWatchlistMutationBody = AddToWatchlistBody
    export type AddToWatchlistMutationError = AxiosError<unknown>

    /**
 * @summary Add symbols (optionally create list)
 */
export const useAddToWatchlist = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addToWatchlist>>, TError,{data: AddToWatchlistBody}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof addToWatchlist>>,
        TError,
        {data: AddToWatchlistBody},
        TContext
      > => {

      const mutationOptions = getAddToWatchlistMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Remove symbol from default or named list
 */
export const removeFromWatchlist = (
    symbol: string,
    params?: RemoveFromWatchlistParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    return axios.default.delete(
      `/api/v1/watchlist/${symbol}`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getRemoveFromWatchlistMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeFromWatchlist>>, TError,{symbol: string;params?: RemoveFromWatchlistParams}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof removeFromWatchlist>>, TError,{symbol: string;params?: RemoveFromWatchlistParams}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof removeFromWatchlist>>, {symbol: string;params?: RemoveFromWatchlistParams}> = (props) => {
          const {symbol,params} = props ?? {};

          return  removeFromWatchlist(symbol,params,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RemoveFromWatchlistMutationResult = NonNullable<Awaited<ReturnType<typeof removeFromWatchlist>>>
    
    export type RemoveFromWatchlistMutationError = AxiosError<unknown>

    /**
 * @summary Remove symbol from default or named list
 */
export const useRemoveFromWatchlist = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeFromWatchlist>>, TError,{symbol: string;params?: RemoveFromWatchlistParams}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof removeFromWatchlist>>,
        TError,
        {symbol: string;params?: RemoveFromWatchlistParams},
        TContext
      > => {

      const mutationOptions = getRemoveFromWatchlistMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Historical outcomes (linked to run_id)
 */
export const listHistory = (
    params?: ListHistoryParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<HistoryRow[]>> => {
    
    return axios.default.get(
      `/api/v1/history`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getListHistoryQueryKey = (params?: ListHistoryParams,) => {
    return [`/api/v1/history`, ...(params ? [params]: [])] as const;
    }

    
export const getListHistoryQueryOptions = <TData = Awaited<ReturnType<typeof listHistory>>, TError = AxiosError<unknown>>(params?: ListHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listHistory>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListHistoryQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listHistory>>> = ({ signal }) => listHistory(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listHistory>>, TError, TData> & { queryKey: QueryKey }
}

export type ListHistoryQueryResult = NonNullable<Awaited<ReturnType<typeof listHistory>>>
export type ListHistoryQueryError = AxiosError<unknown>

/**
 * @summary Historical outcomes (linked to run_id)
 */
export const useListHistory = <TData = Awaited<ReturnType<typeof listHistory>>, TError = AxiosError<unknown>>(
 params?: ListHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listHistory>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getListHistoryQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Read redacted YAML-backed settings
 */
export const getSettings = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Settings>> => {
    
    return axios.default.get(
      `/api/v1/settings`,options
    );
  }


export const getGetSettingsQueryKey = () => {
    return [`/api/v1/settings`] as const;
    }

    
export const getGetSettingsQueryOptions = <TData = Awaited<ReturnType<typeof getSettings>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSettings>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSettingsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSettings>>> = ({ signal }) => getSettings({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSettings>>, TError, TData> & { queryKey: QueryKey }
}

export type GetSettingsQueryResult = NonNullable<Awaited<ReturnType<typeof getSettings>>>
export type GetSettingsQueryError = AxiosError<unknown>

/**
 * @summary Read redacted YAML-backed settings
 */
export const useGetSettings = <TData = Awaited<ReturnType<typeof getSettings>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSettings>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetSettingsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Update settings (validated)
 */
export const putSettings = (
    settings: Settings, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Settings>> => {
    
    return axios.default.put(
      `/api/v1/settings`,
      settings,options
    );
  }



export const getPutSettingsMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putSettings>>, TError,{data: Settings}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof putSettings>>, TError,{data: Settings}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putSettings>>, {data: Settings}> = (props) => {
          const {data} = props ?? {};

          return  putSettings(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutSettingsMutationResult = NonNullable<Awaited<ReturnType<typeof putSettings>>>
    export type PutSettingsMutationBody = Settings
    export type PutSettingsMutationError = AxiosError<unknown>

    /**
 * @summary Update settings (validated)
 */
export const usePutSettings = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putSettings>>, TError,{data: Settings}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof putSettings>>,
        TError,
        {data: Settings},
        TContext
      > => {

      const mutationOptions = getPutSettingsMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Static learning content
 */
export const getLearning = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetLearning200>> => {
    
    return axios.default.get(
      `/api/v1/learning`,options
    );
  }


export const getGetLearningQueryKey = () => {
    return [`/api/v1/learning`] as const;
    }

    
export const getGetLearningQueryOptions = <TData = Awaited<ReturnType<typeof getLearning>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLearning>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLearningQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLearning>>> = ({ signal }) => getLearning({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLearning>>, TError, TData> & { queryKey: QueryKey }
}

export type GetLearningQueryResult = NonNullable<Awaited<ReturnType<typeof getLearning>>>
export type GetLearningQueryError = AxiosError<unknown>

/**
 * @summary Static learning content
 */
export const useGetLearning = <TData = Awaited<ReturnType<typeof getLearning>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLearning>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetLearningQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary List news clusters for a symbol within a time window
 */
export const listNewsBySymbol = (
    params: ListNewsBySymbolParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<NewsListResponse>> => {
    
    return axios.default.get(
      `/api/v1/news`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getListNewsBySymbolQueryKey = (params: ListNewsBySymbolParams,) => {
    return [`/api/v1/news`, ...(params ? [params]: [])] as const;
    }

    
export const getListNewsBySymbolQueryOptions = <TData = Awaited<ReturnType<typeof listNewsBySymbol>>, TError = AxiosError<unknown>>(params: ListNewsBySymbolParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listNewsBySymbol>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListNewsBySymbolQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listNewsBySymbol>>> = ({ signal }) => listNewsBySymbol(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listNewsBySymbol>>, TError, TData> & { queryKey: QueryKey }
}

export type ListNewsBySymbolQueryResult = NonNullable<Awaited<ReturnType<typeof listNewsBySymbol>>>
export type ListNewsBySymbolQueryError = AxiosError<unknown>

/**
 * @summary List news clusters for a symbol within a time window
 */
export const useListNewsBySymbol = <TData = Awaited<ReturnType<typeof listNewsBySymbol>>, TError = AxiosError<unknown>>(
 params: ListNewsBySymbolParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listNewsBySymbol>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getListNewsBySymbolQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Likely catalyst(s) explaining a move at a given time
 */
export const reasonForMove = (
    symbol: string,
    params: ReasonForMoveParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<NewsMoveAttributionResponse>> => {
    
    return axios.default.get(
      `/api/v1/moves/${symbol}/reason`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getReasonForMoveQueryKey = (symbol: string,
    params: ReasonForMoveParams,) => {
    return [`/api/v1/moves/${symbol}/reason`, ...(params ? [params]: [])] as const;
    }

    
export const getReasonForMoveQueryOptions = <TData = Awaited<ReturnType<typeof reasonForMove>>, TError = AxiosError<unknown>>(symbol: string,
    params: ReasonForMoveParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reasonForMove>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReasonForMoveQueryKey(symbol,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof reasonForMove>>> = ({ signal }) => reasonForMove(symbol,params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(symbol), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof reasonForMove>>, TError, TData> & { queryKey: QueryKey }
}

export type ReasonForMoveQueryResult = NonNullable<Awaited<ReturnType<typeof reasonForMove>>>
export type ReasonForMoveQueryError = AxiosError<unknown>

/**
 * @summary Likely catalyst(s) explaining a move at a given time
 */
export const useReasonForMove = <TData = Awaited<ReturnType<typeof reasonForMove>>, TError = AxiosError<unknown>>(
 symbol: string,
    params: ReasonForMoveParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reasonForMove>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getReasonForMoveQueryOptions(symbol,params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Batch ingest of normalized news clusters + summaries
 */
export const ingestNews = (
    newsIngestBatch: NewsIngestBatch, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    return axios.default.post(
      `/api/v1/news/ingest`,
      newsIngestBatch,options
    );
  }



export const getIngestNewsMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof ingestNews>>, TError,{data: NewsIngestBatch}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof ingestNews>>, TError,{data: NewsIngestBatch}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof ingestNews>>, {data: NewsIngestBatch}> = (props) => {
          const {data} = props ?? {};

          return  ingestNews(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type IngestNewsMutationResult = NonNullable<Awaited<ReturnType<typeof ingestNews>>>
    export type IngestNewsMutationBody = NewsIngestBatch
    export type IngestNewsMutationError = AxiosError<unknown>

    /**
 * @summary Batch ingest of normalized news clusters + summaries
 */
export const useIngestNews = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof ingestNews>>, TError,{data: NewsIngestBatch}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof ingestNews>>,
        TError,
        {data: NewsIngestBatch},
        TContext
      > => {

      const mutationOptions = getIngestNewsMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * Returns paginated news clusters grouped by trading window without applying a symbol filter. Provide either `on` (with optional `align`) or an explicit `from`/`to` window.

 * @summary List news across all symbols for a trading window
 */
export const listAllNews = (
    params?: ListAllNewsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<NewsWindowListResponse>> => {
    
    return axios.default.get(
      `/api/v1/news/list`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getListAllNewsQueryKey = (params?: ListAllNewsParams,) => {
    return [`/api/v1/news/list`, ...(params ? [params]: [])] as const;
    }

    
export const getListAllNewsQueryOptions = <TData = Awaited<ReturnType<typeof listAllNews>>, TError = AxiosError<unknown>>(params?: ListAllNewsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAllNews>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListAllNewsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAllNews>>> = ({ signal }) => listAllNews(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAllNews>>, TError, TData> & { queryKey: QueryKey }
}

export type ListAllNewsQueryResult = NonNullable<Awaited<ReturnType<typeof listAllNews>>>
export type ListAllNewsQueryError = AxiosError<unknown>

/**
 * @summary List news across all symbols for a trading window
 */
export const useListAllNews = <TData = Awaited<ReturnType<typeof listAllNews>>, TError = AxiosError<unknown>>(
 params?: ListAllNewsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAllNews>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getListAllNewsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




