/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Quick health (combined) */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["healthLive"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe (SQLite + Parquet availability) */
        get: operations["healthReady"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Prometheus metrics (optional) */
        get: operations["metrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/screener": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Screener rows (filters, sort, pagination) */
        get: operations["listScreener"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger on-demand scan (idempotent) */
        post: operations["postScan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List recent scan runs */
        get: operations["listRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run details */
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/universe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List/search universe (symbols) */
        get: operations["listUniverse"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/universe/sectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sector facets with counts */
        get: operations["listSectors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instruments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search/autocomplete instruments */
        get: operations["listInstruments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instruments/{symbol}/detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Drawer detail for a symbol */
        get: operations["getInstrumentDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instruments/{symbol}/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Price slice for sparkline */
        get: operations["getInstrumentPrices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instruments/{symbol}/indicators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Indicator slice for chart tabs */
        get: operations["getInstrumentIndicators"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List locked positions (optional filter by symbol) */
        get: operations["listPositions"];
        put?: never;
        /** Lock price / anchor baseline */
        post: operations["createPosition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/positions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update note/price/date */
        put: operations["updatePosition"];
        post?: never;
        /** Remove locked position */
        delete: operations["deletePosition"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapshots/pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pin a snapshot for a symbol */
        post: operations["pinSnapshot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapshots/pins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List pins (optionally by symbol) */
        get: operations["listSnapshotPins"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapshots/pin/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a pin */
        delete: operations["unpinSnapshot"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List alert rules and states */
        get: operations["listAlerts"];
        put?: never;
        /** Create alert rule */
        post: operations["createAlert"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update alert rule */
        put: operations["updateAlert"];
        post?: never;
        /** Delete alert rule */
        delete: operations["deleteAlert"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/digest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preview digest (no send) */
        get: operations["previewAlertDigest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watchlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user watchlists & symbols */
        get: operations["getWatchlist"];
        put?: never;
        /** Add symbols (optionally create list) */
        post: operations["addToWatchlist"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watchlist/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove symbol from default or named list */
        delete: operations["removeFromWatchlist"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Historical outcomes (linked to run_id) */
        get: operations["listHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read redacted YAML-backed settings */
        get: operations["getSettings"];
        /** Update settings (validated) */
        put: operations["putSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/learning": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Static learning content */
        get: operations["getLearning"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Canonical uppercase ticker
         * @example RELIANCE
         */
        Symbol: string;
        /**
         * @description UTC timestamp yyyymmddHHMMss
         * @example 20250101153000
         */
        RunId: string;
        RunSummary: {
            run_id: components["schemas"]["RunId"];
            job_name: string;
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            ended_at?: string | null;
            /** @enum {string} */
            status: "PENDING" | "RUNNING" | "SUCCEEDED" | "FAILED";
        };
        RunDetail: components["schemas"]["RunSummary"] & {
            counts?: {
                symbols_processed?: number;
                rows_written?: number;
            };
            error?: string | null;
        };
        Pagination: {
            page?: number;
            per_page?: number;
            total?: number | null;
            next_cursor?: string | null;
        };
        Problem: {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /**
             * @description App-specific error code
             * @enum {string}
             */
            code?: "VALIDATION_ERROR" | "RATE_LIMITED" | "SNAPSHOT_CONFLICT" | "NOT_FOUND";
            errors?: {
                field?: string;
                message?: string;
            }[];
        };
        HealthState: {
            status?: string;
            details?: {
                [key: string]: unknown;
            };
        };
        UniverseInstrument: {
            symbol: components["schemas"]["Symbol"];
            name: string;
            sector?: string;
            active?: boolean;
        };
        SectorFacet: {
            sector?: string;
            count?: number;
        };
        Score: {
            total?: number;
            momentum_12_1m?: number;
            momentum_6m?: number;
            momentum_3m?: number;
            momentum_1m?: number;
            rsi_component?: number;
            adx_component?: number;
            volatility_penalty?: number;
        };
        Badge: {
            key?: string;
            label?: string;
            color?: string;
        };
        ScreenerRow: {
            symbol?: components["schemas"]["Symbol"];
            name?: string;
            sector?: string;
            last?: number;
            change_pct?: number;
            score?: components["schemas"]["Score"];
            badges?: components["schemas"]["Badge"][];
        };
        NextAction: {
            /** @enum {string} */
            action?: "HOLD" | "BUY" | "TRIM" | "EXIT" | "TBD";
            reason?: string;
        };
        DrawerDetail: {
            symbol?: components["schemas"]["Symbol"];
            /** Format: date-time */
            as_of?: string;
            run_id?: components["schemas"]["RunId"];
            score?: components["schemas"]["Score"];
            indicators?: {
                [key: string]: number;
            };
            badges?: components["schemas"]["Badge"][];
            next_action?: components["schemas"]["NextAction"];
        };
        PriceCandle: {
            /** Format: date */
            dt?: string;
            open?: number;
            high?: number;
            low?: number;
            close?: number;
            volume?: number;
        };
        IndicatorPoint: {
            /** Format: date */
            dt?: string;
            /** @enum {string} */
            key?: "rsi" | "adx" | "ema12" | "ema26" | "ema50" | "ema200" | "obv" | "relvol";
            value?: number;
        };
        AlertRule: {
            symbol: components["schemas"]["Symbol"];
            enabled: boolean;
            channels?: {
                email?: boolean;
                desktop?: boolean;
                whatsapp?: boolean;
            };
            conditions?: {
                [key: string]: unknown;
            };
        };
        AlertState: {
            id?: number;
            rule?: components["schemas"]["AlertRule"];
            /** Format: date-time */
            last_fired_at?: string | null;
            /** Format: date-time */
            muted_until?: string | null;
        };
        HistoryRow: {
            run_id?: components["schemas"]["RunId"];
            symbol?: components["schemas"]["Symbol"];
            outcome?: string;
            pnl_pct?: number;
            notes?: string;
        };
        /** @description Redacted YAML-backed settings surfaced to UI */
        Settings: {
            [key: string]: unknown;
        };
        PositionIn: {
            symbol: components["schemas"]["Symbol"];
            price: number;
            /** Format: date-time */
            as_of: string;
            note?: string;
        };
        PositionOut: components["schemas"]["PositionIn"] & {
            id?: number;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        SnapshotPinIn: {
            symbol: components["schemas"]["Symbol"];
            run_id: components["schemas"]["RunId"];
        };
        SnapshotPinOut: components["schemas"]["SnapshotPinIn"] & {
            id?: number;
            /** Format: date-time */
            created_at?: string;
        };
    };
    responses: never;
    parameters: {
        Symbol: components["schemas"]["Symbol"];
        Page: number;
        PerPage: number;
        Cursor: string;
        IfNoneMatch: string;
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: {
        /** @description Entity tag of response payload */
        ETag: string;
        /** @description Seconds to retry after rate limit */
        RetryAfter: string;
        /** @description Request limit window */
        XRateLimitLimit: number;
        /** @description Remaining requests in window */
        XRateLimitRemaining: number;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthState"];
                };
            };
        };
    };
    healthLive: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Live */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    healthReady: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not ready */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    metrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Prometheus exposition */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    listScreener: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                per_page?: components["parameters"]["PerPage"];
                cursor?: components["parameters"]["Cursor"];
                /** @description Sort key (e.g., score.desc, rsi.asc) */
                sort?: string;
                /** @description Filtering DSL via query params, e.g.:
                 *     rsi.gt=70, adx.gt=20, sector.in=IT,FIN, symbol.like=RELI
                 *      */
                filters?: string;
            };
            header?: {
                "If-None-Match"?: components["parameters"]["IfNoneMatch"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Screener page */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["ScreenerRow"][];
                        pagination?: components["schemas"]["Pagination"];
                    };
                };
            };
            /** @description Not Modified */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    postScan: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        run_id?: components["schemas"]["RunId"];
                    };
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    "Retry-After": components["headers"]["RetryAfter"];
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listRuns: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                per_page?: components["parameters"]["PerPage"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Runs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["RunSummary"][];
                        pagination?: components["schemas"]["Pagination"];
                    };
                };
            };
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: components["schemas"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listUniverse: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                per_page?: components["parameters"]["PerPage"];
                q?: string;
                sector?: string;
            };
            header?: {
                "If-None-Match"?: components["parameters"]["IfNoneMatch"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Universe list */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["UniverseInstrument"][];
                        pagination?: components["schemas"]["Pagination"];
                    };
                };
            };
            /** @description Not Modified */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listSectors: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sectors */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectorFacet"][];
                };
            };
        };
    };
    listInstruments: {
        parameters: {
            query?: {
                q?: string;
                page?: components["parameters"]["Page"];
                per_page?: components["parameters"]["PerPage"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Instruments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["UniverseInstrument"][];
                        pagination?: components["schemas"]["Pagination"];
                    };
                };
            };
        };
    };
    getInstrumentDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: components["parameters"]["Symbol"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Drawer detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DrawerDetail"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getInstrumentPrices: {
        parameters: {
            query?: {
                /** @description e.g., 30d, 90d, 1y */
                range?: string;
            };
            header?: never;
            path: {
                symbol: components["parameters"]["Symbol"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OHLCV candles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceCandle"][];
                };
            };
        };
    };
    getInstrumentIndicators: {
        parameters: {
            query?: {
                range?: string;
            };
            header?: never;
            path: {
                symbol: components["parameters"]["Symbol"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Indicator points */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndicatorPoint"][];
                };
            };
        };
    };
    listPositions: {
        parameters: {
            query?: {
                symbol?: components["schemas"]["Symbol"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Positions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionOut"][];
                };
            };
        };
    };
    createPosition: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PositionIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionOut"];
                };
            };
        };
    };
    updatePosition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PositionIn"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionOut"];
                };
            };
        };
    };
    deletePosition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    pinSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SnapshotPinIn"];
            };
        };
        responses: {
            /** @description Pinned */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotPinOut"];
                };
            };
        };
    };
    listSnapshotPins: {
        parameters: {
            query?: {
                symbol?: components["schemas"]["Symbol"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pins */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotPinOut"][];
                };
            };
        };
    };
    unpinSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Unpinned */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listAlerts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Alerts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertState"][];
                };
            };
        };
    };
    createAlert: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertRule"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertState"];
                };
            };
        };
    };
    updateAlert: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertRule"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertState"];
                };
            };
        };
    };
    deleteAlert: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    previewAlertDigest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Digest preview */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    getWatchlist: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Watchlists */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        lists?: {
                            name?: string;
                            symbols?: components["schemas"]["Symbol"][];
                        }[];
                    };
                };
            };
        };
    };
    addToWatchlist: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    symbols: components["schemas"]["Symbol"][];
                };
            };
        };
        responses: {
            /** @description Added */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    removeFromWatchlist: {
        parameters: {
            query?: {
                list?: string;
            };
            header?: never;
            path: {
                symbol: components["parameters"]["Symbol"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listHistory: {
        parameters: {
            query?: {
                date?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description History */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryRow"][];
                };
            };
        };
    };
    getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
        };
    };
    putSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Settings"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
        };
    };
    getLearning: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Content */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
