import pytest
from httpx import AsyncClient, ASGITransport
from asgi_lifespan import LifespanManager
from app.main import app

@pytest.mark.asyncio
async def test_request_id_generated_and_echoed():
    async with LifespanManager(app):
        transport = ASGITransport(app=app)
        async with AsyncClient(transport=transport, base_url="http://test") as ac:
            r = await ac.get("/api/v1/health")
        assert r.status_code == 200
        assert r.headers.get("x-request-id")  # generated by middleware

@pytest.mark.asyncio
async def test_request_id_passthrough_when_provided():
    async with LifespanManager(app):
        transport = ASGITransport(app=app)
        async with AsyncClient(transport=transport, base_url="http://test") as ac:
            r = await ac.get("/api/v1/health", headers={"X-Request-ID": "abc123"})
        assert r.status_code == 200
        assert r.headers.get("x-request-id") == "abc123"
