# app/schemas/runs.py
from __future__ import annotations

"""
Contract-first re-exports for Run* schemas.

We import the generated models produced from openapi.yaml and expose a small,
stable facade for the rest of the app to import from:
    - RunSummaryBase, RunSummary, RunDetail
    - Counts (used inside RunDetail)
    - Pagination (future-proofing)
    - RunsList (object wrapper with 'items' list[RunSummary])

Why this file exists:
- So application code doesn't import from the generated module paths directly.
- Lets us regenerate code without changing import sites.
"""

from pydantic import BaseModel
from app.schemas.generated import models as gen  # generated by datamodel-codegen

# Re-export generated models we use commonly
RunSummaryBase = gen.RunSummaryBase
RunSummary = gen.RunSummary
RunDetail = gen.RunDetail
Counts = gen.Counts
Pagination = gen.Pagination

class RunsList(BaseModel):
    """Wrapper object that contains an array of RunSummary (matches contract)."""
    items: list[RunSummary]

__all__ = [
    "RunSummaryBase",
    "RunSummary",
    "RunDetail",
    "Counts",
    "Pagination",
    "RunsList",
]
