# backend/app/repos/interfaces/base.py
from typing import Protocol, Iterable, Optional
from datetime import datetime
from dataclasses import dataclass

# ---- Common value objects (lightweight; no business logic)
@dataclass
class AlertRuleVO:
    id: int | None
    symbol: str
    rule_type: str           # e.g., "price_crosses", "breakout_enters"
    rule_value: str | None   # e.g., "₹123.45", "EMA10"
    channels: list[str]      # ["email","desktop","whatsapp"]
    enabled: bool
    created_at: datetime
    updated_at: datetime

class IAlertsRepo(Protocol):
    def list_alerts(self) -> list[AlertRuleVO]: ...
    def create_alert(self, rule: AlertRuleVO) -> AlertRuleVO: ...
    def enable_alert(self, alert_id: int, enabled: bool) -> None: ...

class IWatchlistRepo(Protocol):
    def list_symbols(self) -> list[str]: ...
    def upsert_symbol(self, symbol: str, note: str | None = None) -> None: ...
    def remove_symbol(self, symbol: str) -> None: ...

class IHistoryRepo(Protocol):
    def list_history(self, date: Optional[datetime] = None) -> Iterable[dict]: ...

class IJobsRepo(Protocol):
    def record_run(self, run_id: str, started_at: datetime) -> None: ...
    def complete_run(self, run_id: str, ended_at: datetime, status: str, error: str | None = None) -> None: ...

class ISettingsRepo(Protocol):
    def get_yaml(self) -> str:
        ...
    def put_yaml(self, yaml_str: str) -> None:
        ...

class IPositionsRepo(Protocol):
    def list_positions(self, *, symbol: str | None = None, active: bool | None = None) -> list[dict]: ...
    def lock_entry(self, symbol: str, price: float, qty: int | None) -> None: ...
    def update_stop(self, symbol: str, stop_now: float) -> None: ...
    def close_position(self, symbol: str, reason: str) -> None: ...

class ISnapshotPinsRepo(Protocol):
    def pin(self, symbol: str, run_id: str) -> None: ...
    def unpin(self, symbol: str) -> None: ...
    def get_pins(self) -> dict[str, str]: ...
